# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        help_text="Référence unique du tiers (ex: TIER-2025-001234)",
                        max_length=20,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de famille ou raison sociale",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True,
                        help_text="Prénom (pour les particuliers)",
                        max_length=100,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "type_tiers",
                    models.CharField(
                        choices=[
                            ("proprietaire", "Propriétaire"),
                            ("locataire", "Locataire"),
                            ("prestataire", "Prestataire"),
                            ("partenaire", "Partenaire"),
                            ("investisseur", "Investisseur"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type de tiers",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        help_text="Numéro de téléphone principal",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "telephone_secondaire",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone secondaire (optionnel)",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Téléphone secondaire",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adresse email",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        help_text="Adresse complète", verbose_name="Adresse"
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        default="Dakar", max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "quartier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Quartier"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("en_attente", "En attente"),
                            ("archive", "Archivé"),
                        ],
                        db_index=True,
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateField(auto_now_add=True, verbose_name="Date d'ajout"),
                ),
                (
                    "piece_identite",
                    models.FileField(
                        blank=True,
                        help_text="CNI, Passeport, etc.",
                        null=True,
                        upload_to="tiers/pieces_identite/",
                        verbose_name="Pièce d'identité",
                    ),
                ),
                (
                    "piece_identite_numero",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de CNI, Passeport, etc.",
                        max_length=50,
                        verbose_name="Numéro pièce d'identité",
                    ),
                ),
                (
                    "autre_document",
                    models.FileField(
                        blank=True,
                        help_text="Document complémentaire (optionnel)",
                        null=True,
                        upload_to="tiers/documents/",
                        verbose_name="Autre document",
                    ),
                ),
                (
                    "date_entree",
                    models.DateField(
                        blank=True,
                        help_text="Date d'entrée dans le logement (pour les locataires)",
                        null=True,
                        verbose_name="Date d'entrée",
                    ),
                ),
                (
                    "situation_pro",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("salarie", "Salarié"),
                            ("independant", "Indépendant"),
                            ("etudiant", "Étudiant"),
                            ("retraite", "Retraité"),
                            ("chomeur", "Demandeur d'emploi"),
                            ("autre", "Autre"),
                        ],
                        help_text="Pour les locataires",
                        max_length=20,
                        verbose_name="Situation professionnelle",
                    ),
                ),
                (
                    "garant_nom",
                    models.CharField(
                        blank=True,
                        help_text="Pour les locataires",
                        max_length=100,
                        verbose_name="Nom du garant",
                    ),
                ),
                (
                    "garant_tel",
                    models.CharField(
                        blank=True,
                        help_text="Pour les locataires",
                        max_length=17,
                        verbose_name="Téléphone du garant",
                    ),
                ),
                (
                    "type_bailleur",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise", "Entreprise"),
                            ("sci", "SCI"),
                            ("autre", "Autre"),
                        ],
                        default="particulier",
                        help_text="Pour les propriétaires/bailleurs",
                        max_length=20,
                        verbose_name="Type de bailleur",
                    ),
                ),
                (
                    "entreprise",
                    models.CharField(
                        blank=True,
                        help_text="Si bailleur entreprise",
                        max_length=100,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "numero_siret",
                    models.CharField(
                        blank=True,
                        help_text="Pour les entreprises",
                        max_length=14,
                        verbose_name="Numéro SIRET",
                    ),
                ),
                (
                    "adresse_fiscale",
                    models.TextField(
                        blank=True,
                        help_text="Adresse pour les documents fiscaux (si différente de l'adresse principale)",
                        verbose_name="Adresse fiscale",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes et observations sur le tiers",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tiers_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tiers_modifies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte utilisateur associé (si la personne a besoin d'accès au système)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tiers_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiers",
                "verbose_name_plural": "Tiers",
                "ordering": ["-date_ajout", "nom"],
            },
        ),
        migrations.CreateModel(
            name="TiersBien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("vente", "Vente"),
                            ("gestion", "Gestion"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "type_mandat",
                    models.CharField(
                        choices=[
                            ("exclusif", "Mandat exclusif"),
                            ("non_exclusif", "Mandat non exclusif"),
                            ("sans_mandat", "Sans mandat"),
                        ],
                        default="sans_mandat",
                        max_length=20,
                        verbose_name="Type de mandat",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        help_text="Date de début de la relation contractuelle",
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Date de fin prévue ou effective (optionnel)",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                            ("annule", "Annulé"),
                        ],
                        db_index=True,
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "montant_commission",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Commission prévue pour cette relation",
                        max_digits=12,
                        null=True,
                        verbose_name="Montant de la commission (FCFA)",
                    ),
                ),
                (
                    "pourcentage_commission",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pourcentage de commission (si applicable)",
                        max_digits=5,
                        null=True,
                        verbose_name="Pourcentage de commission (%)",
                    ),
                ),
                (
                    "contrat_signe",
                    models.FileField(
                        blank=True,
                        help_text="Document du contrat signé",
                        null=True,
                        upload_to="tiers/contrats/",
                        verbose_name="Contrat signé",
                    ),
                ),
                (
                    "mandat_document",
                    models.FileField(
                        blank=True,
                        help_text="Document de mandat (si applicable)",
                        null=True,
                        upload_to="tiers/mandats/",
                        verbose_name="Document de mandat",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes et observations sur cette relation",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "appartement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers_lies",
                        to="properties.appartement",
                        verbose_name="Appartement",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tiers_biens_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "residence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers_lies",
                        to="properties.residence",
                        verbose_name="Résidence",
                    ),
                ),
                (
                    "tiers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biens_lies",
                        to="tiers.tiers",
                        verbose_name="Tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liaison Tiers-Bien",
                "verbose_name_plural": "Liaisons Tiers-Biens",
                "ordering": ["-date_debut"],
                "indexes": [
                    models.Index(
                        fields=["type_contrat", "statut"],
                        name="tiers_tiers_type_co_c2fcdc_idx",
                    ),
                    models.Index(
                        fields=["-date_debut"], name="tiers_tiers_date_de_4e3ab8_idx"
                    ),
                ],
                "unique_together": {("tiers", "appartement", "type_contrat")},
            },
        ),
        migrations.AddIndex(
            model_name="tiers",
            index=models.Index(
                fields=["type_tiers", "statut"], name="tiers_tiers_type_ti_137fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tiers",
            index=models.Index(
                fields=["nom", "prenom"], name="tiers_tiers_nom_62fb91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tiers",
            index=models.Index(
                fields=["-date_ajout"], name="tiers_tiers_date_aj_494056_idx"
            ),
        ),
    ]
