# Generated by Django 4.2.7 on 2025-10-22 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheRenseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero_fiche', models.CharField(help_text='Généré automatiquement (ex: FICHE-2025-001)', max_length=50, unique=True, verbose_name='Numéro de fiche')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('employeur', models.CharField(blank=True, max_length=200, verbose_name='Employeur')),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('villa', 'Villa'), ('appartement_meuble', 'Appartement meublé'), ('hangar', 'Hangar')], max_length=30, verbose_name='Type de bien')),
                ('adresse_bien', models.TextField(blank=True, verbose_name='Adresse du bien')),
                ('nombre_pieces', models.CharField(blank=True, max_length=100, verbose_name='Nombre de pièces')),
                ('bulletins_salaire_fournis', models.BooleanField(default=False, verbose_name='3 derniers bulletins de salaire')),
                ('piece_identite_fournie', models.BooleanField(default=False, verbose_name="Copie de la pièce d'identité")),
                ('fiche_signee', models.BooleanField(default=False, verbose_name='Fiche de renseignement signée')),
                ('garant_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du garant')),
                ('garant_prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom du garant')),
                ('garant_adresse', models.TextField(blank=True, verbose_name='Adresse du garant')),
                ('garant_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du garant')),
                ('garant_employeur', models.CharField(blank=True, max_length=200, verbose_name='Employeur du garant')),
                ('evaluation_bien', models.TextField(blank=True, verbose_name='Évaluation du bien')),
                ('montant_caution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant de la caution')),
                ('montant_loyer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du loyer')),
                ('montant_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Commission d'agence")),
                ('ancien_bailleur', models.CharField(blank=True, max_length=200, verbose_name='Ancien bailleur')),
                ('ancien_bailleur_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone ancien bailleur')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('date_signature', models.DateField(blank=True, null=True, verbose_name='Date de signature')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='fiches_renseignement/', verbose_name='Fichier PDF')),
                ('signature_client', models.ImageField(blank=True, null=True, upload_to='signatures/clients/', verbose_name='Signature du client')),
                ('signature_entreprise', models.ImageField(blank=True, null=True, upload_to='signatures/entreprise/', verbose_name="Signature de l'entreprise")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de signature'), ('signee', 'Signée'), ('validee', 'Validée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('locataire', models.ForeignKey(blank=True, limit_choices_to={'type_tiers': 'locataire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_renseignement', to='tiers.tiers', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Fiche de renseignement',
                'verbose_name_plural': 'Fiches de renseignement',
                'ordering': ['-created_at'],
            },
        ),
    ]
