# Generated by Django 4.2.7 on 2025-10-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_ficherenseignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiers',
            name='compte_active',
            field=models.BooleanField(default=False, help_text='Indique si le compte utilisateur a été activé par le tiers', verbose_name='Compte activé'),
        ),
        migrations.AddField(
            model_name='tiers',
            name='date_creation_compte',
            field=models.DateTimeField(blank=True, help_text='Date de création du compte utilisateur associé', null=True, verbose_name='Date de création du compte'),
        ),
        migrations.AddField(
            model_name='tiers',
            name='mot_de_passe_temporaire',
            field=models.CharField(blank=True, help_text='Mot de passe temporaire généré lors de la création du compte (sera effacé après première connexion)', max_length=50, verbose_name='Mot de passe temporaire'),
        ),
    ]
