# Generated by Django 4.2.7 on 2025-11-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_tiers_compte_active_tiers_date_creation_compte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='type_tiers',
            field=models.CharField(choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire'), ('coproprietaire', 'Copropriétaire'), ('prestataire', 'Prestataire'), ('partenaire', 'Partenaire'), ('investisseur', 'Investisseur'), ('autre', 'Autre')], db_index=True, max_length=20, verbose_name='Type de tiers'),
        ),
    ]
