# Generated by Django 4.2.7 on 2025-10-22 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "etape_actuelle",
                    models.CharField(
                        choices=[
                            ("verification_dossier", "Vérification des dossiers"),
                            ("attente_facture", "En attente de facture"),
                            ("facture_validee", "Facture validée"),
                            ("redaction_contrat", "Rédaction du contrat"),
                            ("visite_entree", "Visite d'entrée et état des lieux"),
                            ("remise_cles", "Remise des clés"),
                            ("termine", "Terminé - Contrat actif"),
                        ],
                        default="verification_dossier",
                        max_length=30,
                        verbose_name="Étape actuelle",
                    ),
                ),
                (
                    "statut_dossier",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours de vérification"),
                            ("incomplet", "Dossier incomplet"),
                            ("complet", "Dossier complet"),
                        ],
                        default="en_cours",
                        max_length=15,
                        verbose_name="Statut du dossier",
                    ),
                ),
                (
                    "facture_validee_le",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de validation de la facture",
                    ),
                ),
                (
                    "date_visite_entree",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de la visite d'entrée"
                    ),
                ),
                (
                    "lieu_rdv_visite",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Lieu de rendez-vous pour la visite",
                    ),
                ),
                (
                    "rapport_etat_lieux",
                    models.FileField(
                        blank=True,
                        upload_to="pmo/etat_lieux/%Y/%m/",
                        verbose_name="Rapport d'état des lieux (PDF)",
                    ),
                ),
                (
                    "date_remise_cles",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de remise des clés"
                    ),
                ),
                (
                    "nombre_cles",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de clés remises"
                    ),
                ),
                (
                    "notes_pmo",
                    models.TextField(blank=True, verbose_name="Notes internes PMO"),
                ),
                (
                    "observations_visite",
                    models.TextField(
                        blank=True, verbose_name="Observations lors de la visite"
                    ),
                ),
                (
                    "date_envoi_finance",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date d'envoi au service Finance",
                    ),
                ),
                (
                    "date_debut_redaction",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de début de rédaction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow PMO",
                "verbose_name_plural": "Workflows PMO",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentContrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("piece_identite", "Pièce d'identité"),
                            ("quittance_loyer", "Quittance de loyer"),
                            ("bail_precedent", "Bail précédent"),
                            ("justificatif_revenus", "Justificatif de revenus"),
                            ("attestation_employeur", "Attestation employeur"),
                            ("rib", "RIB"),
                            ("etat_lieux_entree", "État des lieux d'entrée"),
                            ("titre_propriete", "Titre de propriété"),
                            ("plan_cadastral", "Plan cadastral"),
                            ("compromis_vente", "Compromis de vente"),
                            ("diagnostic_technique", "Diagnostic technique"),
                            ("autre", "Autre document"),
                        ],
                        max_length=30,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        upload_to="pmo/documents/%Y/%m/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("attendu", "En attente"),
                            ("recu", "Reçu"),
                            ("verifie", "Vérifié"),
                            ("refuse", "Refusé"),
                        ],
                        default="attendu",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_verification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de vérification"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "obligatoire",
                    models.BooleanField(
                        default=True, verbose_name="Document obligatoire"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de contrat",
                "verbose_name_plural": "Documents de contrat",
                "ordering": ["workflow", "type_document"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "etape_precedente",
                    models.CharField(max_length=30, verbose_name="Étape précédente"),
                ),
                (
                    "etape_suivante",
                    models.CharField(max_length=30, verbose_name="Étape suivante"),
                ),
                (
                    "date_transition",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de transition"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
            ],
            options={
                "verbose_name": "Historique workflow",
                "verbose_name_plural": "Historiques workflow",
                "ordering": ["-date_transition"],
            },
        ),
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_contrat",
                    models.CharField(
                        help_text="Numéro unique du contrat (ex: CTR-2025-001)",
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de contrat",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("location_simple", "Location simple"),
                            ("location_meublee", "Location meublée"),
                            ("bail_commercial", "Bail commercial"),
                            ("sous_location", "Sous-location"),
                        ],
                        default="location_simple",
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "duree_mois",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Durée en mois",
                    ),
                ),
                (
                    "loyer_mensuel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Loyer mensuel (FCFA)",
                    ),
                ),
                (
                    "charges_mensuelles",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Charges mensuelles (FCFA)",
                    ),
                ),
                (
                    "depot_garantie",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Dépôt de garantie (FCFA)",
                    ),
                ),
                (
                    "frais_agence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Frais d'agence (FCFA)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("actif", "Actif"),
                            ("expire", "Expiré"),
                            ("resilie", "Résilié"),
                            ("suspendu", "Suspendu"),
                            ("renouvele", "Renouvelé"),
                        ],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_renouvelable",
                    models.BooleanField(
                        default=True, verbose_name="Renouvelable automatiquement"
                    ),
                ),
                (
                    "preavis_mois",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Préavis en mois",
                    ),
                ),
                (
                    "conditions_particulieres",
                    models.TextField(
                        blank=True, verbose_name="Conditions particulières"
                    ),
                ),
                (
                    "fichier_contrat",
                    models.FileField(
                        blank=True,
                        upload_to="contrats/pdf/%Y/%m/",
                        verbose_name="Fichier PDF du contrat",
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de signature"
                    ),
                ),
                (
                    "signe_par_locataire",
                    models.BooleanField(
                        default=False, verbose_name="Signé par le locataire"
                    ),
                ),
                (
                    "signe_par_bailleur",
                    models.BooleanField(
                        default=False, verbose_name="Signé par le bailleur"
                    ),
                ),
                (
                    "notes_internes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
            ],
            options={
                "verbose_name": "Contrat de location",
                "verbose_name_plural": "Contrats de location",
                "ordering": ["-date_debut", "-created_at"],
            },
        ),
    ]
