# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0001_initial"),
        ("properties", "0001_initial"),
        ("payments", "0001_initial"),
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalcontract",
            name="appartement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrats",
                to="properties.appartement",
                verbose_name="Appartement loué",
            ),
        ),
        migrations.AddField(
            model_name="rentalcontract",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrats_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="rentalcontract",
            name="locataire",
            field=models.ForeignKey(
                limit_choices_to={"type_tiers": "locataire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrats",
                to="tiers.tiers",
                verbose_name="Locataire",
            ),
        ),
        migrations.AddField(
            model_name="historiqueworkflow",
            name="effectue_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Effectué par",
            ),
        ),
        migrations.AddField(
            model_name="historiqueworkflow",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique",
                to="contracts.contractworkflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.AddField(
            model_name="documentcontrat",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_verifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifié par",
            ),
        ),
        migrations.AddField(
            model_name="documentcontrat",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="contracts.contractworkflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.AddField(
            model_name="contractworkflow",
            name="cles_remises_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remises_cles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Clés remises par",
            ),
        ),
        migrations.AddField(
            model_name="contractworkflow",
            name="contrat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow",
                to="contracts.rentalcontract",
                verbose_name="Contrat",
            ),
        ),
        migrations.AddField(
            model_name="contractworkflow",
            name="facture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_contrat",
                to="payments.invoice",
                verbose_name="Facture associée",
            ),
        ),
        migrations.AddField(
            model_name="contractworkflow",
            name="responsable_pmo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflows_pmo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable PMO",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(
                fields=["numero_contrat"], name="contracts_r_numero__91d6d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(
                fields=["appartement", "statut"], name="contracts_r_apparte_4682fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(
                fields=["locataire", "statut"], name="contracts_r_locatai_756994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(
                fields=["date_debut", "date_fin"], name="contracts_r_date_de_7a8687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(fields=["statut"], name="contracts_r_statut_50e41c_idx"),
        ),
        migrations.AddIndex(
            model_name="historiqueworkflow",
            index=models.Index(
                fields=["workflow", "-date_transition"],
                name="contracts_h_workflo_cd5a0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historiqueworkflow",
            index=models.Index(
                fields=["effectue_par"], name="contracts_h_effectu_9fd1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentcontrat",
            index=models.Index(
                fields=["workflow", "statut"], name="contracts_d_workflo_c574f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentcontrat",
            index=models.Index(
                fields=["type_document"], name="contracts_d_type_do_8622b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractworkflow",
            index=models.Index(
                fields=["etape_actuelle"], name="contracts_c_etape_a_3e1102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractworkflow",
            index=models.Index(
                fields=["statut_dossier"], name="contracts_c_statut__aebe24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractworkflow",
            index=models.Index(
                fields=["responsable_pmo"], name="contracts_c_respons_61a5a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractworkflow",
            index=models.Index(
                fields=["date_visite_entree"], name="contracts_c_date_vi_ae13e5_idx"
            ),
        ),
    ]
