# Generated by Django 4.2.7 on 2025-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='type_contrat_usage',
            field=models.CharField(choices=[('habitation', "Contrat à Usage d'Habitation"), ('professionnel', 'Contrat à Usage Professionnel')], default='habitation', help_text='Détermine les clauses applicables au contrat', max_length=20, verbose_name='Usage du contrat'),
        ),
    ]
