# Generated by Django 4.2.7 on 2025-10-23 19:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rentalcontract_type_contrat_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='travaux_realises',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Coût des travaux de rénovation ou d'aménagement avant la location", max_digits=10, verbose_name='Travaux réalisés (FCFA)'),
        ),
    ]
