# Generated by Django 4.2.7 on 2025-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_add_travaux_realises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontrat',
            name='type_document',
            field=models.CharField(choices=[('piece_identite', "Pièce d'identité"), ('quittance_loyer', 'Quittance de loyer'), ('bail_precedent', 'Bail précédent'), ('justificatif_revenus', 'Justificatif de revenus'), ('attestation_employeur', 'Attestation employeur'), ('rib', 'RIB'), ('etat_lieux_entree', "État des lieux d'entrée"), ('ninea', 'Document NINEA'), ('rccm', 'Document RCCM'), ('titre_propriete', 'Titre de propriété'), ('plan_cadastral', 'Plan cadastral'), ('compromis_vente', 'Compromis de vente'), ('diagnostic_technique', 'Diagnostic technique'), ('autre', 'Autre document')], max_length=30, verbose_name='Type de document'),
        ),
    ]
