# Generated by Django 4.2.7 on 2025-11-04 11:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_documentcontrat_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la TVA calculé automatiquement', max_digits=10, verbose_name='Montant TVA (FCFA)'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TVA applicable (18% pour contrats professionnels, 0% pour habitation)', max_digits=5, verbose_name='Taux de TVA (%)'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='frais_agence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Frais d'agence ajustables - peut être modifié manuellement", max_digits=8, verbose_name="Frais d'agence (FCFA)"),
        ),
    ]
