# Generated by Django 4.2.7 on 2025-10-22 20:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "date_snapshot",
                    models.DateField(unique=True, verbose_name="Date du snapshot"),
                ),
                (
                    "total_biens",
                    models.PositiveIntegerField(default=0, verbose_name="Total biens"),
                ),
                (
                    "biens_occupes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Biens occupés"
                    ),
                ),
                (
                    "biens_libres",
                    models.PositiveIntegerField(default=0, verbose_name="Biens libres"),
                ),
                (
                    "taux_occupation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux d'occupation (%)",
                    ),
                ),
                (
                    "revenus_mensuels",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Revenus mensuels",
                    ),
                ),
                (
                    "depenses_mensuelles",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Dépenses mensuelles",
                    ),
                ),
                (
                    "benefice_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Bénéfice net",
                    ),
                ),
                (
                    "factures_en_attente",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Factures en attente"
                    ),
                ),
                (
                    "montant_en_attente",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant en attente",
                    ),
                ),
                (
                    "factures_en_retard",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Factures en retard"
                    ),
                ),
                (
                    "montant_en_retard",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant en retard",
                    ),
                ),
                (
                    "interventions_ouvertes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Interventions ouvertes"
                    ),
                ),
                (
                    "interventions_urgentes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Interventions urgentes"
                    ),
                ),
                (
                    "interventions_en_retard",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Interventions en retard"
                    ),
                ),
                (
                    "employes_actifs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Employés actifs"
                    ),
                ),
                (
                    "taches_en_cours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tâches en cours"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques dashboard",
                "verbose_name_plural": "Statistiques dashboard",
                "ordering": ["-date_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du KPI"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("pourcentage", "%"),
                            ("euro", "€"),
                            ("nombre", "Unité"),
                            ("jours", "Jours"),
                        ],
                        max_length=20,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "valeur_actuelle",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valeur actuelle",
                    ),
                ),
                (
                    "valeur_objectif",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valeur objectif",
                    ),
                ),
                (
                    "valeur_precedente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valeur précédente",
                    ),
                ),
                (
                    "tendance",
                    models.CharField(
                        choices=[
                            ("hausse", "Hausse"),
                            ("baisse", "Baisse"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        max_length=10,
                        verbose_name="Tendance",
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        choices=[
                            ("green", "Vert"),
                            ("orange", "Orange"),
                            ("red", "Rouge"),
                            ("blue", "Bleu"),
                        ],
                        default="blue",
                        max_length=10,
                        verbose_name="Couleur d'affichage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "date_derniere_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="UserDashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict, verbose_name="Configuration du layout"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Clair"),
                            ("dark", "Sombre"),
                            ("auto", "Automatique"),
                        ],
                        default="light",
                        max_length=20,
                        verbose_name="Thème",
                    ),
                ),
                (
                    "widgets_actifs",
                    models.JSONField(default=list, verbose_name="Widgets actifs"),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300,
                        verbose_name="Intervalle de rafraîchissement (secondes)",
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Notifications activées"
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence dashboard",
                "verbose_name_plural": "Préférences dashboard",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du widget")),
                (
                    "type_widget",
                    models.CharField(
                        choices=[
                            ("stat_card", "Carte statistique"),
                            ("chart_line", "Graphique linéaire"),
                            ("chart_bar", "Graphique en barres"),
                            ("chart_pie", "Graphique camembert"),
                            ("table", "Tableau"),
                            ("list", "Liste"),
                        ],
                        max_length=20,
                        verbose_name="Type de widget",
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(default=0, verbose_name="Position X"),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(default=0, verbose_name="Position Y"),
                ),
                (
                    "largeur",
                    models.PositiveIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Largeur (colonnes)",
                    ),
                ),
                (
                    "hauteur",
                    models.PositiveIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Hauteur (lignes)",
                    ),
                ),
                (
                    "source_donnees",
                    models.CharField(
                        choices=[
                            ("properties", "Biens immobiliers"),
                            ("payments", "Paiements"),
                            ("interventions", "Interventions"),
                            ("tasks", "Tâches"),
                            ("expenses", "Dépenses"),
                            ("kpis", "KPIs"),
                        ],
                        max_length=50,
                        verbose_name="Source de données",
                    ),
                ),
                (
                    "filtres",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Filtres appliqués"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration du widget"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visible"),
                ),
                (
                    "couleur_theme",
                    models.CharField(
                        choices=[
                            ("primary", "Primaire"),
                            ("secondary", "Secondaire"),
                            ("success", "Succès"),
                            ("warning", "Avertissement"),
                            ("danger", "Danger"),
                            ("info", "Information"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="Couleur du thème",
                    ),
                ),
                (
                    "donnees_cache",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données en cache"
                    ),
                ),
                (
                    "date_cache",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du cache"
                    ),
                ),
                (
                    "duree_cache_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Durée du cache (minutes)"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un widget global",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget dashboard",
                "verbose_name_plural": "Widgets dashboard",
                "ordering": ["position_y", "position_x"],
                "unique_together": {("utilisateur", "nom")},
            },
        ),
    ]
