# Generated by Django 4.2.7 on 2025-10-24 23:09

from django.db import migrations


def convert_employee_types(apps, schema_editor):
    """
    Convertit les anciens types 'field_agent' et 'technician' vers 'employe'
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')

    # Compter les conversions pour le rapport
    field_agents_count = CustomUser.objects.filter(user_type='field_agent').count()
    technicians_count = CustomUser.objects.filter(user_type='technician').count()

    # Convertir field_agent → employe
    CustomUser.objects.filter(user_type='field_agent').update(user_type='employe')

    # Convertir technician → employe
    CustomUser.objects.filter(user_type='technician').update(user_type='employe')

    print(f"[OK] Migration des types d'employes:")
    print(f"   - {field_agents_count} 'field_agent' -> 'employe'")
    print(f"   - {technicians_count} 'technician' -> 'employe'")
    print(f"   - Total: {field_agents_count + technicians_count} utilisateurs convertis")


def reverse_conversion(apps, schema_editor):
    """
    Fonction de rollback - ne peut pas deviner les types originaux
    """
    print("[ATTENTION] La migration inverse ne peut pas restaurer les types originaux.")
    print("   Tous les employes resteront de type 'employe'.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_employee_types, reverse_conversion),
    ]
