# Generated by Django 4.2.7 on 2025-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_convert_employee_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('accountant', 'Comptable'), ('employe', 'Employé'), ('tenant', 'Locataire'), ('landlord', 'Bailleur')], default='tenant', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
