# Generated by Django 5.0.7 on 2025-10-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mot_de_passe_temporaire',
            field=models.BooleanField(default=False, help_text="Si True, l'utilisateur devra changer son mot de passe à la prochaine connexion", verbose_name='Mot de passe temporaire'),
        ),
    ]
