# Generated by Django 4.2.7 on 2025-10-22 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appartement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Référence unique de l'appartement (ex: APP-001)",
                        max_length=20,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Appartement 3A, Bureau 12, Studio Rose",
                        max_length=200,
                        verbose_name="Nom/Numéro",
                    ),
                ),
                (
                    "etage",
                    models.IntegerField(
                        default=0,
                        help_text="0 pour RDC, -1 pour sous-sol",
                        verbose_name="Étage",
                    ),
                ),
                (
                    "type_bien",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("apartment", "Appartement"),
                            ("f1", "F1 (1 pièce)"),
                            ("f2", "F2 (2 pièces)"),
                            ("f3", "F3 (3 pièces)"),
                            ("f4", "F4 (4 pièces)"),
                            ("f5_plus", "F5+ (5 pièces et plus)"),
                            ("duplex", "Duplex"),
                            ("penthouse", "Penthouse"),
                            ("villa", "Villa"),
                            ("commercial", "Local commercial"),
                            ("office", "Bureau"),
                            ("warehouse", "Entrepôt"),
                        ],
                        max_length=20,
                        verbose_name="Type d'appartement",
                    ),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Superficie (m²)",
                    ),
                ),
                (
                    "surface_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Champ de compatibilité - utilise superficie",
                        max_digits=8,
                        null=True,
                        verbose_name="Surface Area (m²)",
                    ),
                ),
                (
                    "nb_pieces",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Nombre de pièces",
                    ),
                ),
                (
                    "rooms_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Champ de compatibilité - utilise nb_pieces",
                        null=True,
                        verbose_name="Rooms Count",
                    ),
                ),
                (
                    "nb_chambres",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de chambres"
                    ),
                ),
                (
                    "bedrooms_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Champ de compatibilité - utilise nb_chambres",
                        null=True,
                        verbose_name="Bedrooms Count",
                    ),
                ),
                (
                    "nb_sdb",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de salles de bain"
                    ),
                ),
                (
                    "bathrooms_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Champ de compatibilité - utilise nb_sdb",
                        null=True,
                        verbose_name="Bathrooms Count",
                    ),
                ),
                (
                    "nb_wc",
                    models.PositiveIntegerField(default=1, verbose_name="Nombre de WC"),
                ),
                (
                    "is_meuble",
                    models.BooleanField(default=False, verbose_name="Meublé"),
                ),
                (
                    "is_furnished",
                    models.BooleanField(
                        default=False,
                        help_text="Champ de compatibilité - utilise is_meuble",
                        verbose_name="Is Furnished",
                    ),
                ),
                (
                    "has_balcon",
                    models.BooleanField(default=False, verbose_name="Balcon/Terrasse"),
                ),
                (
                    "has_parking",
                    models.BooleanField(default=False, verbose_name="Place de parking"),
                ),
                (
                    "has_climatisation",
                    models.BooleanField(default=False, verbose_name="Climatisation"),
                ),
                (
                    "equipements_inclus",
                    models.TextField(
                        blank=True,
                        help_text="Réfrigérateur, lave-linge, TV, etc.",
                        verbose_name="Équipements inclus",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Champ de compatibilité - utilise equipements_inclus",
                        verbose_name="Amenities",
                    ),
                ),
                (
                    "statut_occupation",
                    models.CharField(
                        choices=[
                            ("available", "Libre"),
                            ("libre", "Libre"),
                            ("occupied", "Occupé"),
                            ("occupe", "Occupé"),
                            ("maintenance", "En maintenance"),
                            ("reserved", "Réservé"),
                            ("reserve", "Réservé"),
                            ("hors_service", "Hors service"),
                        ],
                        default="libre",
                        max_length=20,
                        verbose_name="Statut d'occupation",
                    ),
                ),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("available", "Libre"),
                            ("libre", "Libre"),
                            ("occupied", "Occupé"),
                            ("occupe", "Occupé"),
                            ("maintenance", "En maintenance"),
                            ("reserved", "Réservé"),
                            ("reserve", "Réservé"),
                            ("hors_service", "Hors service"),
                        ],
                        default="available",
                        help_text="Champ de compatibilité - utilise statut_occupation",
                        max_length=20,
                        verbose_name="Occupancy Status",
                    ),
                ),
                (
                    "mode_location",
                    models.CharField(
                        choices=[
                            ("short_term", "Courte durée"),
                            ("courte_duree", "Courte durée (- 3 mois)"),
                            ("long_term", "Longue durée"),
                            ("longue_duree", "Longue durée (+ 3 mois)"),
                            ("saisonniere", "Saisonnière"),
                            ("both", "Les deux"),
                        ],
                        default="longue_duree",
                        max_length=20,
                        verbose_name="Mode de location",
                    ),
                ),
                (
                    "rental_mode",
                    models.CharField(
                        choices=[
                            ("short_term", "Courte durée"),
                            ("courte_duree", "Courte durée (- 3 mois)"),
                            ("long_term", "Longue durée"),
                            ("longue_duree", "Longue durée (+ 3 mois)"),
                            ("saisonniere", "Saisonnière"),
                            ("both", "Les deux"),
                        ],
                        default="long_term",
                        help_text="Champ de compatibilité - utilise mode_location",
                        max_length=20,
                        verbose_name="Rental Mode",
                    ),
                ),
                (
                    "loyer_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Loyer de base (FCFA)",
                    ),
                ),
                (
                    "base_rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Champ de compatibilité - utilise loyer_base",
                        max_digits=10,
                        null=True,
                        verbose_name="Base Rent (FCFA)",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Charges mensuelles (FCFA)",
                    ),
                ),
                (
                    "depot_garantie",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Dépôt de garantie (FCFA)",
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Champ de compatibilité - utilise depot_garantie",
                        max_digits=10,
                        null=True,
                        verbose_name="Security Deposit (FCFA)",
                    ),
                ),
                (
                    "frais_agence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Frais d'agence (FCFA)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "notes_internes",
                    models.TextField(
                        blank=True,
                        help_text="Notes visibles uniquement par l'équipe",
                        verbose_name="Notes internes",
                    ),
                ),
                (
                    "date_derniere_renovation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date dernière rénovation"
                    ),
                ),
                (
                    "date_mise_en_location",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date mise en location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appartement",
                "verbose_name_plural": "Appartements",
                "ordering": ["residence__nom", "etage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="AppartementMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_media",
                    models.CharField(
                        choices=[
                            ("photo_principale", "Photo principale"),
                            ("photo_interieur", "Photo intérieur"),
                            ("photo_exterieur", "Photo extérieur"),
                            ("plan", "Plan de l'appartement"),
                            ("document_legal", "Document légal"),
                            ("video_visite", "Vidéo de visite"),
                            ("facture", "Facture"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de média",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="appartements/medias/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Une seule photo principale par appartement",
                        verbose_name="Média principal",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Visible sur le portail locataire",
                        verbose_name="Visible publiquement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média d'appartement",
                "verbose_name_plural": "Médias d'appartements",
                "ordering": ["ordre", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EtatDesLieux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_etat",
                    models.CharField(
                        help_text="Généré automatiquement (ex: EDL-E-2025-001 ou EDL-S-2025-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro d'état des lieux",
                    ),
                ),
                (
                    "type_etat",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                        verbose_name="Type d'état des lieux",
                    ),
                ),
                (
                    "date_etat",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de l'état des lieux",
                    ),
                ),
                (
                    "commercial_imany",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Commercial IMANY"
                    ),
                ),
                (
                    "observation_globale",
                    models.TextField(blank=True, verbose_name="Observation globale"),
                ),
                (
                    "signe_bailleur",
                    models.BooleanField(
                        default=False, verbose_name="Signé par le bailleur"
                    ),
                ),
                (
                    "signe_locataire",
                    models.BooleanField(
                        default=False, verbose_name="Signé par le locataire"
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de signature"
                    ),
                ),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="etats_lieux/pdf/",
                        verbose_name="Fichier PDF",
                    ),
                ),
            ],
            options={
                "verbose_name": "État des lieux",
                "verbose_name_plural": "États des lieux",
                "ordering": ["-date_etat"],
            },
        ),
        migrations.CreateModel(
            name="EtatDesLieuxDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "piece",
                    models.CharField(
                        help_text="Ex: Salon, Chambre 1, Cuisine, etc.",
                        max_length=100,
                        verbose_name="Pièce",
                    ),
                ),
                (
                    "corps_etat",
                    models.CharField(
                        help_text="Ex: Murs, Sol, Plafond, Fenêtres, Portes, etc.",
                        max_length=200,
                        verbose_name="Corps d'état",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="État, dégâts éventuels, remarques",
                        verbose_name="Observations",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Détail état des lieux",
                "verbose_name_plural": "Détails états des lieux",
                "ordering": ["ordre", "piece"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Référence"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom du bien")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("apartment", "Appartement"),
                            ("villa", "Villa"),
                            ("commercial", "Local commercial"),
                            ("office", "Bureau"),
                            ("warehouse", "Entrepôt"),
                        ],
                        max_length=20,
                        verbose_name="Type de bien",
                    ),
                ),
                ("address", models.TextField(verbose_name="Adresse")),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Quartier"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Dakar", max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "surface_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Superficie (m²)",
                    ),
                ),
                (
                    "rooms_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de pièces"
                    ),
                ),
                (
                    "bedrooms_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de chambres"
                    ),
                ),
                (
                    "bathrooms_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de salles de bain"
                    ),
                ),
                (
                    "is_furnished",
                    models.BooleanField(default=False, verbose_name="Meublé"),
                ),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("available", "Libre"),
                            ("occupied", "Occupé"),
                            ("maintenance", "En maintenance"),
                            ("reserved", "Réservé"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Statut d'occupation",
                    ),
                ),
                (
                    "rental_mode",
                    models.CharField(
                        choices=[
                            ("short_term", "Courte durée"),
                            ("long_term", "Longue durée"),
                            ("both", "Les deux"),
                        ],
                        default="long_term",
                        max_length=20,
                        verbose_name="Mode de location",
                    ),
                ),
                (
                    "base_rent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Loyer de base (FCFA)",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Charges (FCFA)",
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Dépôt de garantie (FCFA)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Équipements"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bien immobilier (Legacy)",
                "verbose_name_plural": "Biens immobiliers (Legacy)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemiseDesCles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_attestation",
                    models.CharField(
                        help_text="Généré automatiquement (ex: RDC-E-2025-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro d'attestation",
                    ),
                ),
                (
                    "type_remise",
                    models.CharField(
                        choices=[
                            ("entree", "Remise à l'entrée"),
                            ("sortie", "Restitution à la sortie"),
                        ],
                        max_length=10,
                        verbose_name="Type de remise",
                    ),
                ),
                (
                    "date_remise",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date de remise"
                    ),
                ),
                (
                    "heure_remise",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de remise"
                    ),
                ),
                (
                    "nombre_cles_appartement",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de clés de l'appartement"
                    ),
                ),
                (
                    "nombre_cles_boite_lettres",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de clés de boîte aux lettres"
                    ),
                ),
                (
                    "nombre_cles_garage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de clés de garage/parking"
                    ),
                ),
                (
                    "nombre_badges",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de badges d'accès"
                    ),
                ),
                (
                    "nombre_telecommandes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de télécommandes"
                    ),
                ),
                (
                    "autres_equipements",
                    models.TextField(
                        blank=True,
                        help_text="Ex: Clés de cave, interphone, etc.",
                        verbose_name="Autres équipements remis",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                (
                    "remis_par",
                    models.CharField(
                        help_text="Nom de la personne qui remet les clés",
                        max_length=100,
                        verbose_name="Remis par",
                    ),
                ),
                (
                    "recu_par",
                    models.CharField(
                        help_text="Nom de la personne qui reçoit les clés",
                        max_length=100,
                        verbose_name="Reçu par",
                    ),
                ),
                (
                    "signe_bailleur",
                    models.BooleanField(
                        default=False, verbose_name="Signé par le bailleur/représentant"
                    ),
                ),
                (
                    "signe_locataire",
                    models.BooleanField(
                        default=False, verbose_name="Signé par le locataire"
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de signature"
                    ),
                ),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="remises_cles/pdf/",
                        verbose_name="Fichier PDF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remise des clés",
                "verbose_name_plural": "Remises des clés",
                "ordering": ["-date_remise"],
            },
        ),
        migrations.CreateModel(
            name="Residence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Référence unique de la résidence (ex: RES-001)",
                        max_length=20,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Résidence Les Palmiers, Immeuble Dakar Plaza",
                        max_length=200,
                        verbose_name="Nom de la résidence",
                    ),
                ),
                (
                    "type_residence",
                    models.CharField(
                        choices=[
                            ("immeuble", "Immeuble"),
                            ("villa_divisee", "Villa divisée"),
                            ("complexe", "Complexe résidentiel"),
                            ("batiment_commercial", "Bâtiment commercial"),
                        ],
                        default="immeuble",
                        max_length=20,
                        verbose_name="Type de résidence",
                    ),
                ),
                ("adresse", models.TextField(verbose_name="Adresse complète")),
                ("quartier", models.CharField(max_length=100, verbose_name="Quartier")),
                (
                    "ville",
                    models.CharField(
                        default="Dakar", max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "nb_etages",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Nombre d'étages",
                    ),
                ),
                (
                    "nb_appartements_total",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Nombre total d'appartements",
                    ),
                ),
                (
                    "annee_construction",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="Année de construction",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("en_construction", "En construction"),
                            ("maintenance", "En maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "equipements",
                    models.TextField(
                        blank=True,
                        help_text="Ascenseur, parking, gardien, etc.",
                        verbose_name="Équipements communs",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résidence",
                "verbose_name_plural": "Résidences",
                "ordering": ["nom", "-created_at"],
            },
        ),
    ]
