# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0002_initial"),
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="proprietaire",
            field=models.ForeignKey(
                limit_choices_to={"type_tiers": "proprietaire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residences",
                to="tiers.tiers",
                verbose_name="Propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="remisedescles",
            name="appartement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remises_cles",
                to="properties.appartement",
                verbose_name="Appartement",
            ),
        ),
        migrations.AddField(
            model_name="remisedescles",
            name="contrat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remises_cles",
                to="contracts.rentalcontract",
                verbose_name="Contrat",
            ),
        ),
        migrations.AddField(
            model_name="remisedescles",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remises_cles_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="remisedescles",
            name="etat_lieux",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remises_cles",
                to="properties.etatdeslieux",
                verbose_name="État des lieux associé",
            ),
        ),
        migrations.AddField(
            model_name="remisedescles",
            name="locataire",
            field=models.ForeignKey(
                limit_choices_to={"type_tiers": "locataire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remises_cles",
                to="tiers.tiers",
                verbose_name="Locataire",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="landlord",
            field=models.ForeignKey(
                limit_choices_to={"type_tiers": "proprietaire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties_legacy",
                to="tiers.tiers",
                verbose_name="Propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="etatdeslieuxdetail",
            name="etat_lieux",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="properties.etatdeslieux",
                verbose_name="État des lieux",
            ),
        ),
        migrations.AddField(
            model_name="etatdeslieux",
            name="appartement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etats_lieux",
                to="properties.appartement",
                verbose_name="Appartement",
            ),
        ),
        migrations.AddField(
            model_name="etatdeslieux",
            name="contrat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etats_lieux",
                to="contracts.rentalcontract",
                verbose_name="Contrat",
            ),
        ),
        migrations.AddField(
            model_name="etatdeslieux",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etats_lieux_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="etatdeslieux",
            name="locataire",
            field=models.ForeignKey(
                limit_choices_to={"type_tiers": "locataire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etats_lieux",
                to="tiers.tiers",
                verbose_name="Locataire",
            ),
        ),
        migrations.AddField(
            model_name="appartementmedia",
            name="appartement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="properties.appartement",
                verbose_name="Appartement",
            ),
        ),
        migrations.AddField(
            model_name="appartement",
            name="residence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appartements",
                to="properties.residence",
                verbose_name="Résidence",
            ),
        ),
        migrations.AddIndex(
            model_name="residence",
            index=models.Index(
                fields=["reference"], name="properties__referen_89efa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="residence",
            index=models.Index(
                fields=["proprietaire", "statut"], name="properties__proprie_e920bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="residence",
            index=models.Index(
                fields=["ville", "quartier"], name="properties__ville_83a3d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appartement",
            index=models.Index(
                fields=["reference"], name="properties__referen_d8f9e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appartement",
            index=models.Index(
                fields=["residence", "statut_occupation"],
                name="properties__residen_aaff01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appartement",
            index=models.Index(
                fields=["type_bien", "mode_location"],
                name="properties__type_bi_12fabc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appartement",
            index=models.Index(
                fields=["loyer_base"], name="properties__loyer_b_f5ce7e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appartement",
            unique_together={("residence", "nom")},
        ),
    ]
