# Generated by Django 4.2.7 on 2025-11-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='type_gestion',
            field=models.CharField(choices=[('location', 'Gestion locative'), ('syndic', 'Syndic de copropriété'), ('mixte', 'Mixte (location + syndic)')], default='location', help_text='Définit si Imany gère cette résidence en location, en tant que syndic, ou les deux', max_length=20, verbose_name='Type de gestion'),
        ),
    ]
