# Generated by Django 4.2.7 on 2025-11-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0004_alter_tiers_type_tiers'),
        ('properties', '0003_residence_type_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour gestion locative/mixte, optionnel pour syndic', limit_choices_to={'type_tiers': 'proprietaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='tiers.tiers', verbose_name='Propriétaire'),
        ),
    ]
