# Generated by Django 4.2.7 on 2025-10-22 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la période"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Période clôturée"),
                ),
                (
                    "date_cloture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                (
                    "total_revenus",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total revenus",
                    ),
                ),
                (
                    "total_depenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total dépenses",
                    ),
                ),
                (
                    "resultat_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Résultat net",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Période comptable",
                "verbose_name_plural": "Périodes comptables",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_expense",
                    models.CharField(
                        help_text="Généré automatiquement",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de dépense",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("reparation", "Réparation"),
                            ("amenagement", "Aménagement"),
                            ("marketing", "Marketing"),
                            ("assurance", "Assurance"),
                            ("taxes", "Taxes et impôts"),
                            ("fournitures", "Fournitures"),
                            ("transport", "Transport"),
                            ("communication", "Communication"),
                            ("salaires", "Salaires"),
                            ("autres", "Autres"),
                        ],
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=200, verbose_name="Titre de la dépense"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                ("date_expense", models.DateField(verbose_name="Date de la dépense")),
                (
                    "fournisseur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fournisseur"
                    ),
                ),
                (
                    "numero_facture_fournisseur",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numéro facture fournisseur",
                    ),
                ),
                (
                    "moyen_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("carte", "Carte bancaire"),
                            ("orange_money", "Orange Money"),
                            ("wave", "Wave"),
                        ],
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validé"),
                            ("paye", "Payé"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "facture_fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/invoices/",
                        verbose_name="Facture",
                    ),
                ),
                (
                    "recu_paiement",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/",
                        verbose_name="Reçu de paiement",
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "is_deductible",
                    models.BooleanField(
                        default=True, verbose_name="Déductible fiscalement"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date_expense", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandlordStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_releve",
                    models.CharField(
                        help_text="Généré automatiquement",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de relevé",
                    ),
                ),
                ("periode_debut", models.DateField(verbose_name="Début de période")),
                ("periode_fin", models.DateField(verbose_name="Fin de période")),
                (
                    "total_encaisse",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total encaissé",
                    ),
                ),
                (
                    "commission_agence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Commission agence",
                    ),
                ),
                (
                    "total_depenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total dépenses",
                    ),
                ),
                (
                    "montant_a_verser",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant à verser",
                    ),
                ),
                (
                    "nb_biens_concernes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de biens concernés"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoye", "Envoyé"),
                            ("paye", "Payé"),
                        ],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "moyen_envoi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        max_length=15,
                        verbose_name="Moyen d'envoi",
                    ),
                ),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="statements/pdf/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Relevé propriétaire",
                "verbose_name_plural": "Relevés propriétaires",
                "ordering": ["-periode_fin", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandlordStatementDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "montant_loyer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant loyer",
                    ),
                ),
                (
                    "montant_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant charges",
                    ),
                ),
                (
                    "total_depenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Total dépenses",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Commission (%)",
                    ),
                ),
                (
                    "commission_montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Commission (montant)",
                    ),
                ),
                (
                    "net_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Net bailleur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail relevé bailleur",
                "verbose_name_plural": "Détails relevés bailleurs",
                "ordering": ["bien__reference"],
            },
        ),
        migrations.CreateModel(
            name="TaxDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_declaration",
                    models.CharField(
                        choices=[
                            ("tva", "TVA"),
                            ("impot_societe", "Impôt sur les sociétés"),
                            ("contribution_fonciere", "Contribution foncière"),
                            ("autres", "Autres"),
                        ],
                        max_length=25,
                        verbose_name="Type de déclaration",
                    ),
                ),
                (
                    "montant_du",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Montant dû",
                    ),
                ),
                ("date_echeance", models.DateField(verbose_name="Date d'échéance")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("calcule", "Calculé"),
                            ("declare", "Déclaré"),
                            ("paye", "Payé"),
                            ("en_retard", "En retard"),
                        ],
                        default="calcule",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "fichier_declaration",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tax/declarations/",
                        verbose_name="Fichier de déclaration",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations_fiscales",
                        to="accounting.accountingperiod",
                        verbose_name="Période comptable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Déclaration fiscale",
                "verbose_name_plural": "Déclarations fiscales",
                "ordering": ["-date_echeance"],
            },
        ),
    ]
