# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0001_initial"),
        ("accounting", "0001_initial"),
        ("properties", "0001_initial"),
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordstatementdetail",
            name="bien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.property",
                verbose_name="Bien",
            ),
        ),
        migrations.AddField(
            model_name="landlordstatementdetail",
            name="contrat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.rentalcontract",
                verbose_name="Contrat",
            ),
        ),
        migrations.AddField(
            model_name="landlordstatementdetail",
            name="releve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="accounting.landlordstatement",
                verbose_name="Relevé",
            ),
        ),
        migrations.AddField(
            model_name="landlordstatement",
            name="genere_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="releves_generes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Généré par",
            ),
        ),
        migrations.AddField(
            model_name="landlordstatement",
            name="proprietaire",
            field=models.ForeignKey(
                limit_choices_to={"type_tiers": "proprietaire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releves",
                to="tiers.tiers",
                verbose_name="Propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="bien",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide pour les dépenses générales",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="properties.property",
                verbose_name="Bien concerné",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="saisie_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses_saisies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Saisi par",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses_validees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validé par",
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="cloture_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Clôturé par",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxdeclaration",
            unique_together={("periode", "type_declaration")},
        ),
        migrations.AddIndex(
            model_name="landlordstatement",
            index=models.Index(
                fields=["numero_releve"], name="accounting__numero__31d8a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landlordstatement",
            index=models.Index(
                fields=["periode_debut", "periode_fin"],
                name="accounting__periode_1051b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landlordstatement",
            index=models.Index(fields=["statut"], name="accounting__statut_dcee87_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="landlordstatement",
            unique_together={("proprietaire", "periode_debut", "periode_fin")},
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["numero_expense"], name="accounting__numero__2bf499_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["categorie"], name="accounting__categor_c755c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["date_expense"], name="accounting__date_ex_a0d16e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["statut"], name="accounting__statut_975b58_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="accountingperiod",
            unique_together={("date_debut", "date_fin")},
        ),
    ]
