# Generated by Django 4.2.7 on 2025-11-09 13:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_residence_type_gestion'),
        ('tiers', '0004_alter_tiers_type_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coproprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nombre_tantiemes', models.IntegerField(help_text='Nombre de tantièmes détenus par ce copropriétaire dans cette copropriété', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de tantièmes')),
                ('quote_part', models.DecimalField(decimal_places=2, editable=False, help_text='Pourcentage de la copropriété détenu (calculé automatiquement)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Quote-part (%)')),
                ('date_entree', models.DateField(help_text="Date d'acquisition des parts", verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(blank=True, help_text='Date de cession des parts', null=True, verbose_name='Date de sortie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur ce copropriétaire', null=True)),
            ],
            options={
                'verbose_name': 'Copropriétaire',
                'verbose_name_plural': 'Copropriétaires',
                'ordering': ['-quote_part', 'tiers__nom'],
            },
        ),
        migrations.CreateModel(
            name='CotisationSyndic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence')),
                ('periode', models.CharField(help_text='Format: 2025-Q1, 2025-Q2, 2025-M01, etc.', max_length=20, verbose_name='Période')),
                ('annee', models.IntegerField(help_text='Année de la cotisation', verbose_name='Année')),
                ('montant_theorique', models.DecimalField(decimal_places=2, help_text='Montant calculé selon les tantièmes', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant théorique')),
                ('montant_percu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant réellement payé', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant perçu')),
                ('date_emission', models.DateField(help_text='Date de création de la cotisation', verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(help_text='Date limite de paiement', verbose_name="Date d'échéance")),
                ('date_paiement_complet', models.DateField(blank=True, help_text='Date à laquelle la cotisation a été totalement payée', null=True, verbose_name='Date de paiement complet')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('paye', 'Payé'), ('impaye', 'Impayé'), ('annule', 'Annulé')], default='a_venir', max_length=20, verbose_name='Statut')),
                ('nombre_relances', models.IntegerField(default=0, verbose_name='Nombre de relances')),
                ('date_derniere_relance', models.DateTimeField(blank=True, null=True, verbose_name='Date dernière relance')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur cette cotisation', null=True)),
                ('coproprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotisations', to='syndic.coproprietaire', verbose_name='Copropriétaire')),
            ],
            options={
                'verbose_name': 'Cotisation syndic',
                'verbose_name_plural': 'Cotisations syndic',
                'ordering': ['-annee', '-periode', 'coproprietaire__tiers__nom'],
            },
        ),
        migrations.CreateModel(
            name='Copropriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nombre_tantiemes_total', models.IntegerField(help_text='Nombre total de tantièmes dans la copropriété (ex: 10000)', validators=[django.core.validators.MinValueValidator(1)])),
                ('periode_cotisation', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='trimestriel', max_length=20, verbose_name='Période de cotisation')),
                ('budget_annuel', models.DecimalField(decimal_places=2, help_text="Budget annuel prévisionnel pour l'entretien des parties communes", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_debut_gestion', models.DateField(help_text='Date à laquelle Imany a commencé la gestion de cette copropriété', verbose_name='Date de début de gestion')),
                ('compte_bancaire', models.CharField(blank=True, help_text='IBAN du compte bancaire de la copropriété', max_length=34, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur la copropriété', null=True)),
                ('residence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copropriete', to='properties.residence', verbose_name='Résidence')),
            ],
            options={
                'verbose_name': 'Copropriété',
                'verbose_name_plural': 'Copropriétés',
                'ordering': ['residence__nom'],
            },
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='copropriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coproprietaires', to='syndic.copropriete', verbose_name='Copropriété'),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='lots',
            field=models.ManyToManyField(blank=True, help_text='Appartements/lots détenus par ce copropriétaire', related_name='coproprietaire', to='properties.appartement', verbose_name='Lots'),
        ),
        migrations.AddField(
            model_name='coproprietaire',
            name='tiers',
            field=models.ForeignKey(limit_choices_to={'type_tiers__contains': 'coproprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='coproprietes', to='tiers.tiers', verbose_name='Copropriétaire'),
        ),
        migrations.CreateModel(
            name='BudgetPrevisionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('annee', models.IntegerField(help_text='Année du budget prévisionnel', verbose_name='Année')),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Montant total du budget', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total')),
                ('date_ag', models.DateField(blank=True, help_text="Date de l'assemblée générale de vote", null=True, verbose_name='Date AG')),
                ('date_vote', models.DateField(blank=True, help_text='Date de vote du budget', null=True, verbose_name='Date de vote')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('propose', 'Proposé'), ('vote', 'Voté'), ('en_cours', "En cours d'exécution"), ('cloture', 'Clôturé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text='Notes et observations', null=True)),
                ('document', models.FileField(blank=True, help_text="PV d'AG, budget détaillé, etc.", null=True, upload_to='syndic/budgets/', verbose_name='Document')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='syndic.copropriete', verbose_name='Copropriété')),
            ],
            options={
                'verbose_name': 'Budget prévisionnel',
                'verbose_name_plural': 'Budgets prévisionnels',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='PaiementCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('autre', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Numéro de chèque, référence virement, etc.', max_length=100, null=True, verbose_name='Référence de paiement')),
                ('recu_genere', models.BooleanField(default=False, verbose_name='Reçu généré')),
                ('notes', models.TextField(blank=True, help_text='Notes sur ce paiement', null=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='syndic.cotisationsyndic', verbose_name='Cotisation')),
            ],
            options={
                'verbose_name': 'Paiement cotisation',
                'verbose_name_plural': 'Paiements cotisations',
                'ordering': ['-date_paiement'],
                'indexes': [models.Index(fields=['cotisation', 'date_paiement'], name='syndic_paie_cotisat_732458_idx'), models.Index(fields=['mode_paiement', 'date_paiement'], name='syndic_paie_mode_pa_d5e1d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.CharField(choices=[('entretien_courant', 'Entretien courant'), ('jardinage', 'Jardinage'), ('nettoyage', 'Nettoyage'), ('gardiennage', 'Gardiennage'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('assurance', 'Assurance'), ('reparations', 'Réparations'), ('travaux', 'Travaux'), ('honoraires_syndic', 'Honoraires syndic'), ('charges_bancaires', 'Charges bancaires'), ('provisions', 'Provisions'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant prévu')),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, help_text='Montant réellement dépensé', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant réalisé')),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette ligne budgétaire', null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='syndic.budgetprevisionnel', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Ligne de budget',
                'verbose_name_plural': 'Lignes de budget',
                'ordering': ['categorie', 'description'],
                'indexes': [models.Index(fields=['budget', 'categorie'], name='syndic_lign_budget__1a0e49_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cotisationsyndic',
            index=models.Index(fields=['statut', 'date_echeance'], name='syndic_coti_statut_2ee5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisationsyndic',
            index=models.Index(fields=['coproprietaire', 'statut'], name='syndic_coti_copropr_44bb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisationsyndic',
            index=models.Index(fields=['annee', 'periode'], name='syndic_coti_annee_4c092a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotisationsyndic',
            unique_together={('coproprietaire', 'periode', 'annee')},
        ),
        migrations.AddIndex(
            model_name='copropriete',
            index=models.Index(fields=['is_active', 'date_debut_gestion'], name='syndic_copr_is_acti_194a48_idx'),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['copropriete', 'is_active'], name='syndic_copr_copropr_307009_idx'),
        ),
        migrations.AddIndex(
            model_name='coproprietaire',
            index=models.Index(fields=['tiers', 'is_active'], name='syndic_copr_tiers_i_1a5218_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coproprietaire',
            unique_together={('tiers', 'copropriete')},
        ),
        migrations.AddIndex(
            model_name='budgetprevisionnel',
            index=models.Index(fields=['copropriete', 'annee'], name='syndic_budg_copropr_560a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetprevisionnel',
            index=models.Index(fields=['statut'], name='syndic_budg_statut_df93a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetprevisionnel',
            unique_together={('copropriete', 'annee')},
        ),
    ]
