# Generated by Django 4.2.7 on 2025-10-22 20:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_facture",
                    models.CharField(
                        help_text="Généré automatiquement",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de facture",
                    ),
                ),
                (
                    "type_facture",
                    models.CharField(
                        choices=[
                            ("loyer", "Facture de Loyer"),
                            ("syndic", "Facture Syndic de Copropriété"),
                            ("demande_achat", "Facture Demande d'Achat"),
                            ("prestataire", "Facture Prestataire"),
                            ("charges", "Charges"),
                            ("penalites", "Pénalités"),
                            ("autres", "Autres"),
                        ],
                        default="loyer",
                        max_length=20,
                        verbose_name="Type de facture",
                    ),
                ),
                (
                    "periode_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Début de période"
                    ),
                ),
                (
                    "periode_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de période"
                    ),
                ),
                (
                    "destinataire_nom",
                    models.CharField(
                        blank=True,
                        help_text="Pour factures syndic/prestataire",
                        max_length=200,
                        verbose_name="Nom du destinataire",
                    ),
                ),
                (
                    "destinataire_adresse",
                    models.TextField(
                        blank=True, verbose_name="Adresse du destinataire"
                    ),
                ),
                (
                    "destinataire_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email du destinataire"
                    ),
                ),
                (
                    "destinataire_telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Téléphone du destinataire",
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant HT",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant TTC",
                    ),
                ),
                ("date_emission", models.DateField(verbose_name="Date d'émission")),
                ("date_echeance", models.DateField(verbose_name="Date d'échéance")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("emise", "Émise"),
                            ("payee", "Payée"),
                            ("en_retard", "En retard"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la facture",
                        verbose_name="Description",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "reference_copropriete",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence copropriété"
                    ),
                ),
                (
                    "trimestre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("T1", "Trimestre 1 (Jan-Mar)"),
                            ("T2", "Trimestre 2 (Avr-Jui)"),
                            ("T3", "Trimestre 3 (Jul-Sep)"),
                            ("T4", "Trimestre 4 (Oct-Déc)"),
                        ],
                        max_length=10,
                        verbose_name="Trimestre",
                    ),
                ),
                (
                    "fournisseur_nom",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nom du fournisseur/prestataire",
                    ),
                ),
                (
                    "fournisseur_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence fournisseur"
                    ),
                ),
                (
                    "type_prestation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plomberie", "Plomberie"),
                            ("electricite", "Électricité"),
                            ("menuiserie", "Menuiserie"),
                            ("peinture", "Peinture"),
                            ("nettoyage", "Nettoyage"),
                            ("jardinage", "Jardinage"),
                            ("securite", "Sécurité"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Type de prestation",
                    ),
                ),
                (
                    "numero_bon_commande",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numéro de bon de commande",
                    ),
                ),
                (
                    "categorie_achat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("materiel", "Matériel"),
                            ("fournitures", "Fournitures"),
                            ("equipement", "Équipement"),
                            ("consommables", "Consommables"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie d'achat",
                    ),
                ),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/pdf/%Y/%m/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "fichier_pdf_nom",
                    models.CharField(
                        blank=True,
                        help_text="Nom pour le fichier PDF (sans extension)",
                        max_length=255,
                        verbose_name="Nom personnalisé du fichier PDF",
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="True si créée manuellement (pas liée à un contrat)",
                        verbose_name="Facture manuelle",
                    ),
                ),
                (
                    "contrat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour factures manuelles (syndic, prestataire, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="contracts.rentalcontract",
                        verbose_name="Contrat",
                    ),
                ),
                (
                    "creee_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-date_emission", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "type_rappel",
                    models.CharField(
                        choices=[("automatique", "Automatique"), ("manuel", "Manuel")],
                        default="automatique",
                        max_length=15,
                        verbose_name="Type de rappel",
                    ),
                ),
                (
                    "moyen_envoi",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=15,
                        verbose_name="Moyen d'envoi",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message envoyé")),
                (
                    "statut",
                    models.CharField(
                        choices=[("envoye", "Envoyé"), ("echec", "Échec")],
                        default="envoye",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "envoye_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Envoyé par",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rappels",
                        to="payments.invoice",
                        verbose_name="Facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rappel de paiement",
                "verbose_name_plural": "Rappels de paiement",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_paiement",
                    models.CharField(
                        help_text="Généré automatiquement",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de paiement",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant payé",
                    ),
                ),
                ("date_paiement", models.DateField(verbose_name="Date de paiement")),
                (
                    "moyen_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("carte", "Carte bancaire"),
                            ("orange_money", "Orange Money"),
                            ("wave", "Wave"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence de transaction",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("refuse", "Refusé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="payments.invoice",
                        verbose_name="Facture",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["numero_paiement"],
                        name="payments_pa_numero__a5ec6f_idx",
                    ),
                    models.Index(
                        fields=["date_paiement"], name="payments_pa_date_pa_66784e_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="payments_pa_statut_f9d7ac_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["numero_facture"], name="payments_in_numero__d75e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["type_facture"], name="payments_in_type_fa_cd391e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["statut"], name="payments_in_statut_d3fd42_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["date_emission"], name="payments_in_date_em_fce1aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["date_echeance"], name="payments_in_date_ec_dc1ae8_idx"
            ),
        ),
    ]
