# Generated by Django 4.2.7 on 2025-10-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_derniere_relance',
            field=models.DateTimeField(blank=True, help_text='Date du dernier rappel de paiement automatique', null=True, verbose_name='Date dernière relance'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_generation_etat_loyer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date génération état loyer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_generation_quittance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date génération quittance'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='etat_loyer_genere',
            field=models.BooleanField(default=False, help_text="True si l'état de loyer a été généré pour le propriétaire", verbose_name='État de loyer généré'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fichier_etat_loyer',
            field=models.FileField(blank=True, help_text="PDF de l'état de loyer pour le propriétaire", null=True, upload_to='invoices/etats_loyer/%Y/%m/', verbose_name='Fichier état de loyer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fichier_quittance',
            field=models.FileField(blank=True, help_text='PDF de la quittance pour le locataire', null=True, upload_to='invoices/quittances/%Y/%m/', verbose_name='Fichier quittance'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nombre_relances',
            field=models.IntegerField(default=0, help_text='Compteur de relances envoyées pour cette facture', verbose_name='Nombre de relances'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quittance_generee',
            field=models.BooleanField(default=False, help_text='True si la quittance a été générée pour le locataire', verbose_name='Quittance générée'),
        ),
    ]
