# Generated by Django 4.2.7 on 2025-10-24 22:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_travail_travailmedia_travailchecklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_add_documents_generation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='banque_cheque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banque émettrice du chèque'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='beneficiaire_cheque',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire du chèque'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commentaire_comptable',
            field=models.TextField(blank=True, verbose_name='Commentaire du comptable'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commentaire_dg',
            field=models.TextField(blank=True, verbose_name='Commentaire de la DG'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commentaire_responsable',
            field=models.TextField(blank=True, verbose_name='Commentaire du responsable'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_demande',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la demande'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_emission_cheque',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'émission du chèque"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception de la marchandise'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_traitement_comptable',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date traitement comptable'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_validation_dg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation DG'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_validation_responsable',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation responsable'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='etape_workflow',
            field=models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('valide_responsable', 'Validé par responsable'), ('comptable', 'En traitement comptable'), ('validation_dg', 'En attente validation DG'), ('approuve', 'Approuvé - En attente achat'), ('en_cours_achat', 'Achat en cours'), ('recue', 'Marchandise reçue'), ('paye', 'Payé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='brouillon', help_text="Pour demandes d'achat uniquement", max_length=25, verbose_name='Étape du workflow'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='motif_principal',
            field=models.TextField(blank=True, verbose_name='Motif principal de la demande'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero_cheque',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receptionne_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_marchandises', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remarques_reception',
            field=models.TextField(blank=True, verbose_name='Remarques sur la réception'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_fonction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service/Fonction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signature_demandeur_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date signature demandeur'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='traite_par_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_traitees_comptable', to=settings.AUTH_USER_MODEL, verbose_name='Traité par (comptable)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='travail_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat_liees', to='maintenance.travail', verbose_name='Travail lié'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='valide_par_dg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees_dg', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (Direction Générale)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='valide_par_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (responsable)'),
        ),
        migrations.CreateModel(
            name='LigneDemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('designation', models.CharField(max_length=255, verbose_name="Désignation de l'article")),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité')),
                ('unite', models.CharField(default='unité', help_text='Ex: unité, mètre, kg, litre, boîte', max_length=50, verbose_name='Unité')),
                ('fournisseur', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur/Partenaire')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire estimé (FCFA)')),
                ('prix_total', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement: quantité × prix unitaire', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix total (FCFA)')),
                ('motif', models.TextField(verbose_name='Motif/Justification pour cet article')),
                ('quantite_recue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantité réellement reçue')),
                ('prix_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix réel payé')),
                ('demande', models.ForeignKey(limit_choices_to={'type_facture': 'demande_achat'}, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_achat', to='payments.invoice', verbose_name="Demande d'achat")),
            ],
            options={
                'verbose_name': "Ligne de demande d'achat",
                'verbose_name_plural': "Lignes de demandes d'achat",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('soumission', 'Soumission pour validation'), ('validation_responsable', 'Validation par responsable'), ('refus_responsable', 'Refus par responsable'), ('traitement_comptable', 'Traitement comptable'), ('preparation_cheque', 'Préparation chèque'), ('validation_dg', 'Validation par DG'), ('refus_dg', 'Refus par DG'), ('approbation', 'Approbation finale'), ('achat', 'Achat effectué'), ('reception', 'Réception marchandise'), ('paiement', 'Paiement effectué'), ('annulation', 'Annulation'), ('modification', 'Modification')], max_length=30, verbose_name='Action')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('ancienne_valeur', models.CharField(blank=True, help_text='Pour les modifications', max_length=50, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.CharField(blank=True, help_text='Pour les modifications', max_length=50, verbose_name='Nouvelle valeur')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validations', to='payments.invoice', verbose_name='Demande')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_validation', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Historique de validation',
                'verbose_name_plural': 'Historiques de validations',
                'ordering': ['-date_action'],
            },
        ),
    ]
