# Generated by Django 4.2.7 on 2025-10-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_demande_achat_field'),
        ('payments', '0003_invoice_banque_cheque_invoice_beneficiaire_cheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='travail_lie',
            field=models.ForeignKey(blank=True, help_text="Travail pour lequel cette demande d'achat a été créée", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to='maintenance.travail', verbose_name='Travail lié'),
        ),
    ]
