# Generated by Django 5.0.7 on 2025-10-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_invoice_travail_lie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception de la marchandise'),
        ),
    ]
