# Generated by Django 4.2.7 on 2025-10-22 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_intervention",
                    models.CharField(
                        help_text="Généré automatiquement",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro d'intervention",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type_intervention",
                    models.CharField(
                        choices=[
                            ("plomberie", "Plomberie"),
                            ("electricite", "Électricité"),
                            ("menage", "Ménage"),
                            ("reparation", "Réparation"),
                            ("peinture", "Peinture"),
                            ("serrurerie", "Serrurerie"),
                            ("climatisation", "Climatisation"),
                            ("jardinage", "Jardinage"),
                            ("securite", "Sécurité"),
                            ("autres", "Autres"),
                        ],
                        max_length=30,
                        verbose_name="Type d'intervention",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=15,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "date_signalement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de signalement"
                    ),
                ),
                (
                    "date_assignation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'assignation"
                    ),
                ),
                (
                    "date_debut",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("signale", "Signalé"),
                            ("assigne", "Assigné"),
                            ("en_cours", "En cours"),
                            ("complete", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="signale",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cout_estime",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Coût estimé",
                    ),
                ),
                (
                    "cout_reel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Coût réel",
                    ),
                ),
                (
                    "commentaire_technicien",
                    models.TextField(blank=True, verbose_name="Commentaire technicien"),
                ),
                (
                    "satisfaction_locataire",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Satisfaction locataire (1-5)",
                    ),
                ),
                (
                    "notes_internes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
            ],
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "ordering": ["-date_signalement"],
            },
        ),
        migrations.CreateModel(
            name="InterventionChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Description de la tâche"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Terminé"),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "date_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de completion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de checklist",
                "verbose_name_plural": "Éléments de checklist",
                "ordering": ["ordre", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterventionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_media",
                    models.CharField(
                        choices=[
                            ("photo_avant", "Photo avant"),
                            ("photo_apres", "Photo après"),
                            ("facture", "Facture"),
                            ("devis", "Devis"),
                            ("rapport", "Rapport"),
                        ],
                        max_length=20,
                        verbose_name="Type de média",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="interventions/medias/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Média d'intervention",
                "verbose_name_plural": "Médias d'interventions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterventionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du template"
                    ),
                ),
                (
                    "type_intervention",
                    models.CharField(
                        choices=[
                            ("plomberie", "Plomberie"),
                            ("electricite", "Électricité"),
                            ("menage", "Ménage"),
                            ("reparation", "Réparation générale"),
                            ("peinture", "Peinture"),
                            ("serrurerie", "Serrurerie"),
                            ("climatisation", "Climatisation"),
                            ("jardinage", "Jardinage"),
                            ("maintenance_preventive", "Maintenance préventive"),
                            ("autres", "Autres"),
                        ],
                        max_length=30,
                        verbose_name="Type d'intervention",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duree_estimee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée estimée (minutes)"
                    ),
                ),
                (
                    "cout_estime",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Coût estimé",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Template actif"),
                ),
            ],
            options={
                "verbose_name": "Template d'intervention",
                "verbose_name_plural": "Templates d'intervention",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="InterventionTemplateChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Description de la tâche"
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_obligatoire",
                    models.BooleanField(default=False, verbose_name="Obligatoire"),
                ),
            ],
            options={
                "verbose_name": "Élément de template checklist",
                "verbose_name_plural": "Éléments de template checklist",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_maintenance",
                    models.CharField(
                        choices=[
                            ("revision_annuelle", "Révision annuelle"),
                            ("nettoyage_mensuel", "Nettoyage mensuel"),
                            ("inspection_trimestre", "Inspection trimestrielle"),
                            ("verification_equipement", "Vérification équipements"),
                            ("entretien_jardin", "Entretien jardin"),
                            ("autres", "Autres"),
                        ],
                        max_length=30,
                        verbose_name="Type de maintenance",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("semestriel", "Semestriel"),
                            ("annuel", "Annuel"),
                        ],
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "prochaine_maintenance",
                    models.DateField(verbose_name="Prochaine maintenance"),
                ),
                (
                    "cout_estime",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Coût estimé",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Programmation active"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Maintenance programmée",
                "verbose_name_plural": "Maintenances programmées",
                "ordering": ["prochaine_maintenance"],
            },
        ),
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre de la tâche"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type_tache",
                    models.CharField(
                        choices=[
                            ("menage", "Ménage"),
                            ("visite", "Visite de contrôle"),
                            ("maintenance_preventive", "Maintenance préventive"),
                            ("etat_lieux", "État des lieux"),
                            ("reparation", "Réparation"),
                            ("livraison", "Livraison"),
                            ("rendez_vous", "Rendez-vous"),
                            ("administrative", "Tâche administrative"),
                            ("autre", "Autre"),
                        ],
                        max_length=25,
                        verbose_name="Type de tâche",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                ("date_prevue", models.DateTimeField(verbose_name="Date prévue")),
                (
                    "duree_estimee",
                    models.DurationField(
                        blank=True,
                        help_text="Format: HH:MM:SS",
                        null=True,
                        verbose_name="Durée estimée",
                    ),
                ),
                (
                    "date_debut",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("complete", "Terminé"),
                            ("annule", "Annulé"),
                            ("reporte", "Reporté"),
                        ],
                        default="planifie",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_recurrente",
                    models.BooleanField(default=False, verbose_name="Tâche récurrente"),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("aucune", "Aucune"),
                            ("quotidien", "Quotidienne"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuelle", "Mensuelle"),
                            ("trimestrielle", "Trimestrielle"),
                            ("annuelle", "Annuelle"),
                        ],
                        default="aucune",
                        max_length=15,
                        verbose_name="Type de récurrence",
                    ),
                ),
                (
                    "recurrence_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de récurrence"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "temps_reel",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Temps réel passé"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche de maintenance",
                "verbose_name_plural": "Tâches de maintenance",
                "ordering": ["date_prevue", "-priorite"],
            },
        ),
    ]
