# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="appartement",
            field=models.ForeignKey(
                blank=True,
                help_text="Peut être null pour une tâche générale",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taches_maintenance",
                to="properties.appartement",
                verbose_name="Appartement concerné",
            ),
        ),
        migrations.AddField(
            model_name="tache",
            name="assigne_a",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "user_type__in": ["employe", "technicien", "agent_terrain"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taches_maintenance_assignees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigné à",
            ),
        ),
        migrations.AddField(
            model_name="tache",
            name="bien",
            field=models.ForeignKey(
                blank=True,
                help_text="Champ de compatibilité - sera supprimé après migration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taches_maintenance_legacy",
                to="properties.property",
                verbose_name="Bien concerné (Legacy)",
            ),
        ),
        migrations.AddField(
            model_name="tache",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taches_maintenance_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceschedule",
            name="appartement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenances_programmees",
                to="properties.appartement",
                verbose_name="Appartement",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceschedule",
            name="bien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenances_programmees_legacy",
                to="properties.property",
                verbose_name="Bien immobilier (Legacy)",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceschedule",
            name="technicien_assigne",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type__in": ["technicien", "agent_terrain"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenances_assignees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Technicien assigné",
            ),
        ),
        migrations.AddField(
            model_name="interventiontemplatechecklistitem",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_template_items",
                to="maintenance.interventiontemplate",
                verbose_name="Template",
            ),
        ),
        migrations.AddField(
            model_name="interventionmedia",
            name="ajoute_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ajouté par",
            ),
        ),
        migrations.AddField(
            model_name="interventionmedia",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="maintenance.intervention",
                verbose_name="Intervention",
            ),
        ),
        migrations.AddField(
            model_name="interventionchecklistitem",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Terminé par",
            ),
        ),
        migrations.AddField(
            model_name="interventionchecklistitem",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="maintenance.intervention",
                verbose_name="Intervention",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="appartement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to="properties.appartement",
                verbose_name="Appartement concerné",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="bien",
            field=models.ForeignKey(
                blank=True,
                help_text="Champ de compatibilité - sera supprimé après migration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions_legacy",
                to="properties.property",
                verbose_name="Bien concerné (Legacy)",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="locataire",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type_tiers": "locataire"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventions_signalees",
                to="tiers.tiers",
                verbose_name="Locataire signataire",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="technicien",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type__in": ["agent_terrain", "technicien"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventions_techniques",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Technicien assigné",
            ),
        ),
        migrations.AddIndex(
            model_name="tache",
            index=models.Index(
                fields=["appartement", "statut"], name="maintenance_apparte_917f3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tache",
            index=models.Index(
                fields=["assigne_a", "statut"], name="maintenance_assigne_657651_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tache",
            index=models.Index(
                fields=["type_tache", "date_prevue"],
                name="maintenance_type_ta_c664a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tache",
            index=models.Index(
                fields=["date_prevue"], name="maintenance_date_pr_e37364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tache",
            index=models.Index(
                fields=["is_recurrente"], name="maintenance_is_recu_4fd3ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(
                fields=["prochaine_maintenance"], name="maintenance_prochai_3d2d4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(
                fields=["frequence"], name="maintenance_frequen_be9ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(
                fields=["is_active"], name="maintenance_is_acti_6d8baa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["numero_intervention"], name="maintenance_numero__62d40a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(fields=["statut"], name="maintenance_statut_df2311_idx"),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["type_intervention"], name="maintenance_type_in_e31d8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["priorite"], name="maintenance_priorit_86fcf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["date_signalement"], name="maintenance_date_si_8e6213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["appartement"], name="maintenance_apparte_67641b_idx"
            ),
        ),
    ]
