# Generated by Django 4.2.7 on 2025-10-24 22:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_tiers_compte_active_tiers_date_creation_compte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_initial'),
        ('payments', '0002_add_documents_generation_fields'),
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero_travail', models.CharField(help_text='Généré automatiquement', max_length=50, unique=True, verbose_name='Numéro de travail')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('nature', models.CharField(choices=[('reactif', 'Réactif (intervention urgente)'), ('planifie', 'Planifié (tâche programmée)'), ('preventif', 'Préventif (maintenance)'), ('projet', 'Projet (travaux importants)')], max_length=15, verbose_name='Nature du travail')),
                ('type_travail', models.CharField(choices=[('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('menuiserie', 'Menuiserie'), ('peinture', 'Peinture'), ('menage', 'Ménage'), ('serrurerie', 'Serrurerie'), ('climatisation', 'Climatisation'), ('jardinage', 'Jardinage'), ('securite', 'Sécurité'), ('vitrerie', 'Vitrerie'), ('maconnerie', 'Maçonnerie'), ('toiture', 'Toiture'), ('etat_lieux', 'État des lieux'), ('visite_controle', 'Visite de contrôle'), ('livraison', 'Livraison'), ('administrative', 'Tâche administrative'), ('autre', 'Autre')], max_length=25, verbose_name='Type de travail')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=15, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('planifie', 'Planifié'), ('assigne', 'Assigné'), ('en_attente_materiel', 'En attente matériel'), ('en_cours', 'En cours'), ('complete', 'Terminé'), ('valide', 'Validé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='signale', max_length=25, verbose_name='Statut')),
                ('date_signalement', models.DateTimeField(blank=True, null=True, verbose_name='Date de signalement')),
                ('date_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue')),
                ('date_assignation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'assignation")),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('duree_estimee', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='Travail récurrent')),
                ('recurrence', models.CharField(choices=[('aucune', 'Aucune'), ('quotidien', 'Quotidienne'), ('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle')], default='aucune', max_length=15, verbose_name='Type de récurrence')),
                ('recurrence_fin', models.DateField(blank=True, null=True, verbose_name='Fin de récurrence')),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coût estimé (FCFA)')),
                ('cout_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coût réel (FCFA)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('satisfaction', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Satisfaction (1-5)')),
                ('temps_reel', models.DurationField(blank=True, null=True, verbose_name='Temps réel passé')),
                ('appartement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='properties.appartement', verbose_name='Appartement concerné')),
                ('assigne_a', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['employe', 'technicien', 'agent_terrain']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('demande_achat', models.ForeignKey(blank=True, limit_choices_to={'type_facture': 'demande_achat'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_lies', to='payments.invoice', verbose_name="Demande d'achat liée")),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='properties.residence', verbose_name='Résidence concernée')),
                ('signale_par', models.ForeignKey(blank=True, limit_choices_to={'type_tiers': 'locataire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_signales', to='tiers.tiers', verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Travail',
                'verbose_name_plural': 'Travaux',
                'ordering': ['-created_at', '-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='TravailMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_media', models.CharField(choices=[('photo_avant', 'Photo avant travaux'), ('photo_apres', 'Photo après travaux'), ('photo_probleme', 'Photo du problème'), ('facture', 'Facture'), ('devis', 'Devis'), ('bon_commande', 'Bon de commande'), ('rapport', 'Rapport'), ('plan', 'Plan/Schéma'), ('autre', 'Autre')], max_length=20, verbose_name='Type de média')),
                ('fichier', models.FileField(upload_to='travaux/medias/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='maintenance.travail', verbose_name='Travail')),
            ],
            options={
                'verbose_name': 'Média de travail',
                'verbose_name_plural': 'Médias de travaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravailChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('description', models.CharField(max_length=200, verbose_name="Description de l'étape")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Terminé par')),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='maintenance.travail', verbose_name='Travail')),
            ],
            options={
                'verbose_name': 'Checklist de travail',
                'verbose_name_plural': 'Checklists de travaux',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='travail',
            index=models.Index(fields=['numero_travail'], name='maintenance_numero__987ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='travail',
            index=models.Index(fields=['statut', 'priorite'], name='maintenance_statut_fe1042_idx'),
        ),
        migrations.AddIndex(
            model_name='travail',
            index=models.Index(fields=['nature', 'type_travail'], name='maintenance_nature_73a05c_idx'),
        ),
        migrations.AddIndex(
            model_name='travail',
            index=models.Index(fields=['date_prevue'], name='maintenance_date_pr_5a366b_idx'),
        ),
        migrations.AddIndex(
            model_name='travail',
            index=models.Index(fields=['assigne_a', 'statut'], name='maintenance_assigne_f72c34_idx'),
        ),
        migrations.AddIndex(
            model_name='travail',
            index=models.Index(fields=['appartement'], name='maintenance_apparte_4ff90c_idx'),
        ),
        migrations.AddIndex(
            model_name='travail',
            index=models.Index(fields=['residence'], name='maintenance_residen_170fc5_idx'),
        ),
    ]
