# Generated by Django 4.2.7 on 2025-10-24 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0003_travail_travailmedia_travailchecklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'employe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_techniques', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='technicien_assigne',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'employe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'employe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_maintenance_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='travail',
            name='assigne_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'employe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travaux_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
    ]
