# Generated by Django 4.2.7 on 2025-10-22 20:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("technique", "Technique"),
                            ("menage", "Ménage"),
                            ("jardinage", "Jardinage"),
                            ("peinture", "Peinture"),
                            ("plomberie", "Plomberie"),
                            ("electricite", "Électricité"),
                            ("serrurerie", "Serrurerie"),
                            ("climatisation", "Climatisation"),
                            ("polyvalent", "Polyvalent"),
                        ],
                        max_length=50,
                        verbose_name="Spécialité",
                    ),
                ),
                (
                    "date_embauche",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "salaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Salaire mensuel",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("conge", "En congé"),
                            ("maladie", "Arrêt maladie"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "telephone_professionnel",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Téléphone professionnel",
                    ),
                ),
                (
                    "niveau_competence",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        default="intermediaire",
                        max_length=15,
                        verbose_name="Niveau de compétence",
                    ),
                ),
                (
                    "note_moyenne",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Note basée sur les évaluations des interventions",
                        max_digits=3,
                        null=True,
                        verbose_name="Note moyenne (sur 5)",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["-date_embauche"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type_tache",
                    models.CharField(
                        choices=[
                            ("menage", "Ménage"),
                            ("visite", "Visite d'inspection"),
                            ("maintenance_preventive", "Maintenance préventive"),
                            ("etat_lieux", "État des lieux"),
                            ("livraison", "Livraison"),
                            ("administrative", "Tâche administrative"),
                            ("autres", "Autres"),
                        ],
                        max_length=30,
                        verbose_name="Type de tâche",
                    ),
                ),
                ("date_prevue", models.DateTimeField(verbose_name="Date prévue")),
                (
                    "date_debut",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "duree_estimee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée estimée (minutes)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("complete", "Complétée"),
                            ("annule", "Annulée"),
                        ],
                        default="planifie",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=15,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "is_recurrente",
                    models.BooleanField(default=False, verbose_name="Tâche récurrente"),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Type de récurrence",
                    ),
                ),
                (
                    "recurrence_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de récurrence"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, verbose_name="Commentaire de l'employé"
                    ),
                ),
                (
                    "temps_passe",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Temps passé (minutes)"
                    ),
                ),
                (
                    "assigne_a",
                    models.ForeignKey(
                        limit_choices_to={
                            "user_type__in": ["agent_terrain", "technicien"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches_assignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
                "ordering": ["-date_prevue"],
            },
        ),
        migrations.CreateModel(
            name="TaskMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_media",
                    models.CharField(
                        choices=[
                            ("photo_avant", "Photo avant"),
                            ("photo_apres", "Photo après"),
                            ("rapport", "Rapport"),
                            ("facture", "Facture"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de média",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(upload_to="tasks/media/", verbose_name="Fichier"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="employees.task",
                        verbose_name="Tâche",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Téléchargé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média de tâche",
                "verbose_name_plural": "Médias de tâche",
                "ordering": ["-created_at"],
            },
        ),
    ]
