# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="bien",
            field=models.ForeignKey(
                blank=True,
                help_text="Peut être null pour les tâches générales",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taches",
                to="properties.property",
                verbose_name="Bien concerné",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taches_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["statut"], name="employees_t_statut_28f53d_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["date_prevue"], name="employees_t_date_pr_171819_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priorite"], name="employees_t_priorit_5ebe51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["type_tache"], name="employees_t_type_ta_49337b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["specialite"], name="employees_e_special_3488b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["statut"], name="employees_e_statut_4a7c2f_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_available"], name="employees_e_is_avai_700bd9_idx"
            ),
        ),
    ]
