# Generated by Django 4.2.7 on 2025-10-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_mot_de_passe_temporaire'),
        ('employees', '0002_initial'),
    ]

    operations = [
    ]
