# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "portal_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Portail locataire"),
                            ("landlord", "Portail bailleur"),
                            ("employee", "Portail employé"),
                            ("manager", "Portail manager"),
                        ],
                        max_length=20,
                        verbose_name="Type de portail",
                    ),
                ),
                (
                    "date_connexion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de connexion"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Clé de session"
                    ),
                ),
                (
                    "date_deconnexion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de déconnexion"
                    ),
                ),
                (
                    "duree_session_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée de session (minutes)"
                    ),
                ),
                (
                    "pages_visitees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pages visitées"
                    ),
                ),
                (
                    "actions_effectuees",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Actions effectuées"
                    ),
                ),
                (
                    "pays",
                    models.CharField(blank=True, max_length=50, verbose_name="Pays"),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès portail",
                "verbose_name_plural": "Accès portails",
                "ordering": ["-date_connexion"],
            },
        ),
        migrations.CreateModel(
            name="UserPortalPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Clair"),
                            ("dark", "Sombre"),
                            ("auto", "Automatique"),
                        ],
                        default="light",
                        max_length=10,
                        verbose_name="Thème",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("wo", "Wolof"),
                            ("en", "Anglais"),
                        ],
                        default="fr",
                        max_length=5,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "dashboard_layout",
                    models.JSONField(
                        default=dict, verbose_name="Configuration du dashboard"
                    ),
                ),
                (
                    "widgets_favoris",
                    models.JSONField(default=list, verbose_name="Widgets favoris"),
                ),
                (
                    "notifications_desktop",
                    models.BooleanField(
                        default=True, verbose_name="Notifications desktop"
                    ),
                ),
                (
                    "notifications_son",
                    models.BooleanField(
                        default=False, verbose_name="Son des notifications"
                    ),
                ),
                (
                    "menu_collapsed",
                    models.BooleanField(
                        default=False, verbose_name="Menu réduit par défaut"
                    ),
                ),
                (
                    "page_accueil_personnalisee",
                    models.CharField(
                        blank=True,
                        help_text="URL de la page d'accueil préférée",
                        max_length=50,
                        verbose_name="Page d'accueil personnalisée",
                    ),
                ),
                (
                    "elements_par_page",
                    models.PositiveIntegerField(
                        choices=[(10, "10"), (25, "25"), (50, "50"), (100, "100")],
                        default=25,
                        verbose_name="Éléments par page",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Dakar",
                        max_length=50,
                        verbose_name="Fuseau horaire",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence portail utilisateur",
                "verbose_name_plural": "Préférences portail utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="PortalWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du widget")),
                (
                    "portal_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Portail locataire"),
                            ("landlord", "Portail bailleur"),
                            ("employee", "Portail employé"),
                            ("manager", "Portail manager"),
                        ],
                        max_length=20,
                        verbose_name="Type de portail",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("quick_stats", "Statistiques rapides"),
                            ("recent_payments", "Paiements récents"),
                            ("pending_tasks", "Tâches en attente"),
                            ("upcoming_events", "Événements à venir"),
                            ("notifications", "Notifications"),
                            ("quick_actions", "Actions rapides"),
                            ("document_list", "Liste de documents"),
                            ("calendar", "Calendrier"),
                            ("chart", "Graphique"),
                            ("news_feed", "Fil d'actualités"),
                        ],
                        max_length=30,
                        verbose_name="Type de widget",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, verbose_name="Configuration du widget"
                    ),
                ),
                (
                    "roles_autorises",
                    models.JSONField(
                        default=list,
                        help_text="Liste des rôles pouvant voir ce widget",
                        verbose_name="Rôles autorisés",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "colonne",
                    models.PositiveIntegerField(
                        choices=[(1, "Colonne 1"), (2, "Colonne 2"), (3, "Colonne 3")],
                        default=1,
                        verbose_name="Colonne",
                    ),
                ),
                (
                    "hauteur",
                    models.CharField(
                        choices=[
                            ("small", "Petit"),
                            ("medium", "Moyen"),
                            ("large", "Grand"),
                            ("auto", "Automatique"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Hauteur",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Widget actif"),
                ),
                (
                    "is_collapsible",
                    models.BooleanField(default=True, verbose_name="Peut être réduit"),
                ),
                (
                    "is_removable",
                    models.BooleanField(
                        default=True, verbose_name="Peut être supprimé"
                    ),
                ),
                (
                    "cache_duration_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Durée du cache (minutes)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget portail",
                "verbose_name_plural": "Widgets portails",
                "ordering": ["portal_type", "ordre"],
                "unique_together": {("portal_type", "nom")},
            },
        ),
        migrations.CreateModel(
            name="PortalConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du widget")),
                (
                    "portal_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Portail locataire"),
                            ("landlord", "Portail bailleur"),
                            ("employee", "Portail employé"),
                            ("manager", "Portail manager"),
                        ],
                        max_length=20,
                        verbose_name="Type de portail",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("quick_stats", "Statistiques rapides"),
                            ("recent_payments", "Paiements récents"),
                            ("pending_tasks", "Tâches en attente"),
                            ("upcoming_events", "Événements à venir"),
                            ("notifications", "Notifications"),
                            ("quick_actions", "Actions rapides"),
                            ("document_list", "Liste de documents"),
                            ("calendar", "Calendrier"),
                            ("chart", "Graphique"),
                            ("news_feed", "Fil d'actualités"),
                        ],
                        max_length=30,
                        verbose_name="Type de widget",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, verbose_name="Configuration du widget"
                    ),
                ),
                (
                    "roles_autorises",
                    models.JSONField(
                        default=list,
                        help_text="Liste des rôles pouvant voir ce widget",
                        verbose_name="Rôles autorisés",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "colonne",
                    models.PositiveIntegerField(
                        choices=[(1, "Colonne 1"), (2, "Colonne 2"), (3, "Colonne 3")],
                        default=1,
                        verbose_name="Colonne",
                    ),
                ),
                (
                    "hauteur",
                    models.CharField(
                        choices=[
                            ("small", "Petit"),
                            ("medium", "Moyen"),
                            ("large", "Grand"),
                            ("auto", "Automatique"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Hauteur",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Widget actif"),
                ),
                (
                    "is_collapsible",
                    models.BooleanField(default=True, verbose_name="Peut être réduit"),
                ),
                (
                    "is_removable",
                    models.BooleanField(
                        default=True, verbose_name="Peut être supprimé"
                    ),
                ),
                (
                    "cache_duration_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Durée du cache (minutes)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget portail",
                "verbose_name_plural": "Widgets portails",
                "ordering": ["portal_type", "ordre"],
                "unique_together": {("portal_type", "nom")},
            },
        ),
        migrations.CreateModel(
            name="PortalNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "portal_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Portail locataire"),
                            ("landlord", "Portail bailleur"),
                            ("employee", "Portail employé"),
                            ("manager", "Portail manager"),
                        ],
                        max_length=20,
                        verbose_name="Type de portail",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Succès"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("update", "Mise à jour"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL vers laquelle rediriger lors du clic",
                        max_length=500,
                        verbose_name="URL d'action",
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Texte du bouton d'action",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "date_read",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "is_sticky",
                    models.BooleanField(
                        default=False,
                        help_text="Reste affiché même après lecture",
                        verbose_name="Épinglé",
                    ),
                ),
                (
                    "show_popup",
                    models.BooleanField(default=False, verbose_name="Affichage popup"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification portail",
                "verbose_name_plural": "Notifications portails",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="portals_por_user_id_be222b_idx",
                    ),
                    models.Index(
                        fields=["portal_type"], name="portals_por_portal__828c81_idx"
                    ),
                    models.Index(
                        fields=["date_expiration"],
                        name="portals_por_date_ex_107978_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PortalFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "portal_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Portail locataire"),
                            ("landlord", "Portail bailleur"),
                            ("employee", "Portail employé"),
                            ("manager", "Portail manager"),
                        ],
                        max_length=20,
                        verbose_name="Type de portail",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug/Problème"),
                            ("suggestion", "Suggestion"),
                            ("feature_request", "Demande de fonctionnalité"),
                            ("compliment", "Compliment"),
                            ("complaint", "Plainte"),
                            ("question", "Question"),
                        ],
                        max_length=20,
                        verbose_name="Type de retour",
                    ),
                ),
                (
                    "satisfaction_score",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Très insatisfait"),
                            (2, "Insatisfait"),
                            (3, "Neutre"),
                            (4, "Satisfait"),
                            (5, "Très satisfait"),
                        ],
                        null=True,
                        verbose_name="Note de satisfaction",
                    ),
                ),
                ("sujet", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL de la page"
                    ),
                ),
                (
                    "browser_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Informations navigateur"
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portals/feedback/screenshots/",
                        verbose_name="Capture d'écran",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("en_cours", "En cours de traitement"),
                            ("resolu", "Résolu"),
                            ("ferme", "Fermé"),
                            ("reporte", "Reporté"),
                        ],
                        default="nouveau",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("reponse", models.TextField(blank=True, verbose_name="Réponse")),
                (
                    "date_reponse",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réponse"
                    ),
                ),
                (
                    "assigne_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks_assignes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour portail",
                "verbose_name_plural": "Retours portails",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feedback_type"], name="portals_por_feedbac_6fcb74_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="portals_por_statut_8f851a_idx"
                    ),
                    models.Index(
                        fields=["portal_type"], name="portals_por_portal__ffad85_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PortalAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "portal_types",
                    models.JSONField(
                        default=list, verbose_name="Types de portails ciblés"
                    ),
                ),
                (
                    "user_types",
                    models.JSONField(
                        default=list, verbose_name="Types d'utilisateurs ciblés"
                    ),
                ),
                (
                    "type_annonce",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("maintenance", "Maintenance"),
                            ("nouveaute", "Nouveauté"),
                            ("urgent", "Urgent"),
                            ("evenement", "Événement"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Type d'annonce",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                        ],
                        default="normale",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "date_debut",
                    models.DateTimeField(verbose_name="Date de début d'affichage"),
                ),
                (
                    "date_fin",
                    models.DateTimeField(verbose_name="Date de fin d'affichage"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Annonce active"),
                ),
                (
                    "affichage_popup",
                    models.BooleanField(
                        default=False, verbose_name="Affichage en popup"
                    ),
                ),
                (
                    "affichage_banniere",
                    models.BooleanField(
                        default=True, verbose_name="Affichage en bannière"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annonces_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "users_specifiques",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateurs spécifiques",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce portail",
                "verbose_name_plural": "Annonces portails",
                "ordering": ["-date_debut"],
                "indexes": [
                    models.Index(
                        fields=["date_debut", "date_fin"],
                        name="portals_por_date_de_b9c531_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="portals_por_is_acti_283a66_idx"
                    ),
                    models.Index(
                        fields=["type_annonce"], name="portals_por_type_an_1dc64b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PortalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Vue de page"),
                            ("form_submit", "Soumission formulaire"),
                            ("download", "Téléchargement"),
                            ("upload", "Upload"),
                            ("search", "Recherche"),
                            ("filter", "Filtrage"),
                            ("export", "Export"),
                            ("print", "Impression"),
                            ("api_call", "Appel API"),
                        ],
                        max_length=30,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "page_url",
                    models.CharField(max_length=500, verbose_name="URL de la page"),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre de la page"
                    ),
                ),
                (
                    "action_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Détails de l'action"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Temps de réponse (ms)"
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Succès")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "access_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="portals.portalaccess",
                        verbose_name="Session d'accès",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité portail",
                "verbose_name_plural": "Activités portails",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["access_session", "timestamp"],
                        name="portals_por_access__3c9a24_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="portals_por_action__01a1a0_idx"
                    ),
                    models.Index(
                        fields=["page_url"], name="portals_por_page_ur_aadd22_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="portalaccess",
            index=models.Index(
                fields=["user", "date_connexion"], name="portals_por_user_id_966731_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portalaccess",
            index=models.Index(
                fields=["portal_type"], name="portals_por_portal__97be5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portalaccess",
            index=models.Index(
                fields=["ip_address"], name="portals_por_ip_addr_500228_idx"
            ),
        ),
    ]
