# Generated by Django 4.2.7 on 2025-10-22 20:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identifiant unique (ex: WELCOME_TENANT)",
                        max_length=50,
                        unique=True,
                        verbose_name="Code du template",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du template"),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("welcome", "Bienvenue"),
                            ("payment_reminder", "Rappel de paiement"),
                            ("contract_expiry", "Expiration contrat"),
                            ("intervention_assigned", "Intervention assignée"),
                            ("intervention_completed", "Intervention terminée"),
                            ("task_assigned", "Tâche assignée"),
                            ("account_created", "Compte créé"),
                            ("password_reset", "Réinitialisation mot de passe"),
                            ("maintenance_scheduled", "Maintenance programmée"),
                            ("invoice_generated", "Facture générée"),
                            ("payment_received", "Paiement reçu"),
                            ("autres", "Autres"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        max_length=15,
                        verbose_name="Canal de communication",
                    ),
                ),
                (
                    "sujet_template",
                    models.CharField(
                        blank=True,
                        help_text="Utilisé pour les emails",
                        max_length=200,
                        verbose_name="Template du sujet",
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Utilisez {{variable}} pour les variables dynamiques",
                        verbose_name="Template du message",
                    ),
                ),
                (
                    "variables_disponibles",
                    models.JSONField(
                        default=list,
                        help_text="Liste des variables utilisables dans le template",
                        verbose_name="Variables disponibles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Template actif"),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("wo", "Wolof"),
                            ("en", "Anglais"),
                        ],
                        default="fr",
                        max_length=5,
                        verbose_name="Langue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de message",
                "verbose_name_plural": "Templates de messages",
                "ordering": ["nom"],
                "unique_together": {("code", "langue")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("welcome", "Bienvenue"),
                            ("payment_reminder", "Rappel de paiement"),
                            ("contract_expiry", "Expiration contrat"),
                            ("intervention_assigned", "Intervention assignée"),
                            ("intervention_completed", "Intervention terminée"),
                            ("task_assigned", "Tâche assignée"),
                            ("account_created", "Compte créé"),
                            ("password_reset", "Réinitialisation mot de passe"),
                            ("maintenance_scheduled", "Maintenance programmée"),
                            ("invoice_generated", "Facture générée"),
                            ("payment_received", "Paiement reçu"),
                            ("system_alert", "Alerte système"),
                            ("autres", "Autres"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("app", "Application"),
                        ],
                        max_length=15,
                        verbose_name="Canal utilisé",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide",
                                regex="^\\+?1?\\d{8,15}$",
                            )
                        ],
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Adresse email"
                    ),
                ),
                (
                    "sujet",
                    models.CharField(blank=True, max_length=200, verbose_name="Sujet"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("programme", "Programmé"),
                            ("envoye", "Envoyé"),
                            ("echec", "Échec"),
                            ("lu", "Lu"),
                        ],
                        default="en_attente",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_programmee",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date programmée"
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "date_lecture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "tentatives",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de tentatives"
                    ),
                ),
                (
                    "max_tentatives",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Maximum de tentatives"
                    ),
                ),
                (
                    "response_id",
                    models.CharField(
                        blank=True,
                        help_text="ID retourné par le service (WhatsApp/SMS)",
                        max_length=100,
                        verbose_name="ID de réponse du service",
                    ),
                ),
                (
                    "erreur_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "variables_utilisees",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Variables utilisées"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de l'objet lié"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet lié",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_recues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "envoye_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_envoyees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Envoyé par",
                    ),
                ),
                (
                    "template_utilise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.messagetemplate",
                        verbose_name="Template utilisé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "date_stats",
                    models.DateField(unique=True, verbose_name="Date des statistiques"),
                ),
                (
                    "sms_envoyes",
                    models.PositiveIntegerField(default=0, verbose_name="SMS envoyés"),
                ),
                (
                    "sms_delivres",
                    models.PositiveIntegerField(default=0, verbose_name="SMS livrés"),
                ),
                (
                    "whatsapp_envoyes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="WhatsApp envoyés"
                    ),
                ),
                (
                    "whatsapp_delivres",
                    models.PositiveIntegerField(
                        default=0, verbose_name="WhatsApp livrés"
                    ),
                ),
                (
                    "whatsapp_lus",
                    models.PositiveIntegerField(default=0, verbose_name="WhatsApp lus"),
                ),
                (
                    "emails_envoyes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Emails envoyés"
                    ),
                ),
                (
                    "welcomes_envoyes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Messages de bienvenue"
                    ),
                ),
                (
                    "rappels_paiement",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Rappels de paiement"
                    ),
                ),
                (
                    "notifications_interventions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Notifications d'interventions"
                    ),
                ),
                (
                    "total_echecs",
                    models.PositiveIntegerField(default=0, verbose_name="Total échecs"),
                ),
                (
                    "cout_total_sms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Coût total SMS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques notifications",
                "verbose_name_plural": "Statistiques notifications",
                "ordering": ["-date_stats"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "whatsapp_id",
                    models.CharField(
                        help_text="ID du message retourné par l'API WhatsApp",
                        max_length=100,
                        verbose_name="ID WhatsApp",
                    ),
                ),
                (
                    "statut_whatsapp",
                    models.CharField(
                        choices=[
                            ("sent", "Envoyé"),
                            ("delivered", "Livré"),
                            ("read", "Lu"),
                            ("failed", "Échec"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="Statut WhatsApp",
                    ),
                ),
                (
                    "date_delivered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison"
                    ),
                ),
                (
                    "date_read",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "webhook_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données webhook"
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_message",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message WhatsApp",
                "verbose_name_plural": "Messages WhatsApp",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "sms_id",
                    models.CharField(
                        help_text="ID du message retourné par l'API SMS",
                        max_length=100,
                        verbose_name="ID SMS",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("orange", "Orange SMS API"),
                            ("tigo", "Tigo SMS API"),
                            ("bulk_sms", "Bulk SMS"),
                            ("twilio", "Twilio"),
                        ],
                        max_length=20,
                        verbose_name="Fournisseur SMS",
                    ),
                ),
                (
                    "statut_sms",
                    models.CharField(
                        choices=[
                            ("sent", "Envoyé"),
                            ("delivered", "Livré"),
                            ("failed", "Échec"),
                            ("expired", "Expiré"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="Statut SMS",
                    ),
                ),
                (
                    "date_delivered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison"
                    ),
                ),
                (
                    "cout",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="Coût du SMS",
                    ),
                ),
                (
                    "callback_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données callback"
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_message",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message SMS",
                "verbose_name_plural": "Messages SMS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "receive_sms",
                    models.BooleanField(default=True, verbose_name="Recevoir les SMS"),
                ),
                (
                    "receive_whatsapp",
                    models.BooleanField(
                        default=True, verbose_name="Recevoir les WhatsApp"
                    ),
                ),
                (
                    "receive_email",
                    models.BooleanField(
                        default=True, verbose_name="Recevoir les emails"
                    ),
                ),
                (
                    "receive_app_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Recevoir les notifications app"
                    ),
                ),
                (
                    "rappel_paiement",
                    models.BooleanField(
                        default=True, verbose_name="Rappels de paiement"
                    ),
                ),
                (
                    "rappel_paiement_jours",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Rappel X jours avant échéance"
                    ),
                ),
                (
                    "interventions",
                    models.BooleanField(
                        default=True, verbose_name="Notifications d'interventions"
                    ),
                ),
                (
                    "contrats",
                    models.BooleanField(
                        default=True, verbose_name="Notifications de contrats"
                    ),
                ),
                (
                    "taches",
                    models.BooleanField(
                        default=True, verbose_name="Notifications de tâches"
                    ),
                ),
                (
                    "langue_preference",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("wo", "Wolof"),
                            ("en", "Anglais"),
                        ],
                        default="fr",
                        max_length=5,
                        verbose_name="Langue préférée",
                    ),
                ),
                (
                    "heure_debut_notifications",
                    models.TimeField(
                        default="08:00", verbose_name="Heure de début des notifications"
                    ),
                ),
                (
                    "heure_fin_notifications",
                    models.TimeField(
                        default="20:00", verbose_name="Heure de fin des notifications"
                    ),
                ),
                (
                    "notifications_weekend",
                    models.BooleanField(
                        default=False, verbose_name="Notifications le weekend"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration notification",
                "verbose_name_plural": "Configurations notifications",
            },
        ),
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "date_traitement_prevue",
                    models.DateTimeField(verbose_name="Date de traitement prévue"),
                ),
                (
                    "en_cours_traitement",
                    models.BooleanField(
                        default=False, verbose_name="En cours de traitement"
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        blank=True,
                        help_text="ID du processus qui traite la notification",
                        max_length=50,
                        verbose_name="ID du worker",
                    ),
                ),
                (
                    "date_debut_traitement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Début du traitement"
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_item",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "File d'attente notification",
                "verbose_name_plural": "File d'attente notifications",
                "ordering": ["-priorite", "date_traitement_prevue"],
                "indexes": [
                    models.Index(
                        fields=["date_traitement_prevue"],
                        name="notificatio_date_tr_4ab73e_idx",
                    ),
                    models.Index(
                        fields=["priorite"], name="notificatio_priorit_1cc45c_idx"
                    ),
                    models.Index(
                        fields=["en_cours_traitement"],
                        name="notificatio_en_cour_71ab87_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Créée"),
                            ("queued", "Mise en file"),
                            ("processing", "En traitement"),
                            ("sent", "Envoyée"),
                            ("delivered", "Livrée"),
                            ("read", "Lue"),
                            ("failed", "Échec"),
                            ("retry", "Nouvelle tentative"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message de log")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log notification",
                "verbose_name_plural": "Logs notifications",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["notification", "timestamp"],
                        name="notificatio_notific_303515_idx",
                    ),
                    models.Index(
                        fields=["action"], name="notificatio_action_ce23ae_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["destinataire", "statut"], name="notificatio_destina_10ae3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["type_notification"], name="notificatio_type_no_ba8ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["date_programmee"], name="notificatio_date_pr_33cf26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["statut"], name="notificatio_statut_45cc83_idx"),
        ),
    ]
